from __future__ import annotations

import shutil
import tomllib
from pathlib import Path

import pytest

from docs_kit import cli

FIXTURES = Path(__file__).parent / "fixtures"
SPEC = "openapi.json"


def make_repo(base: Path, name: str, fixture: str) -> Path:
    repo = base / name
    repo.mkdir(parents=True)
    shutil.copy(FIXTURES / fixture, repo / SPEC)
    return repo


def strip_spec_prose(text: str) -> str:
    keep = (
        "Canonical specification:",
        "<title>",
    )
    return "\n".join(l for l in text.splitlines() if not any(l.startswith(k) for k in keep))


def test_both_specs_render_identical_pages(tmp_path):
    go = make_repo(tmp_path, "go", "golang.openapi.json")
    py = make_repo(tmp_path, "py", "python.openapi.json")
    assert cli.cmd_refresh(go, SPEC) == 0
    assert cli.cmd_refresh(py, SPEC) == 0
    for rel in (cli.ENDPOINTS_PAGE, cli.API_PAGE, cli.SWAGGER_PAGE):
        assert strip_spec_prose((go / rel).read_text()) == strip_spec_prose((py / rel).read_text()), rel
    assert (go / cli.VENDORED_SPEC).read_bytes() == (go / SPEC).read_bytes()


def test_refresh_is_byte_stable(tmp_path):
    repo = make_repo(tmp_path, "repo", "golang.openapi.json")
    assert cli.cmd_refresh(repo, SPEC) == 0
    before = {rel: (repo / rel).read_bytes() for rel in generated_rels()}
    assert cli.cmd_refresh(repo, SPEC) == 0
    after = {rel: (repo / rel).read_bytes() for rel in generated_rels()}
    assert before == after


def generated_rels():
    return (cli.VENDORED_SPEC, cli.SWAGGER_PAGE, cli.API_PAGE, cli.ENDPOINTS_PAGE)


def test_check_detects_stale_and_missing(tmp_path):
    repo = make_repo(tmp_path, "repo", "golang.openapi.json")
    assert cli.cmd_check(repo, SPEC) == 1  # nothing generated yet
    assert cli.cmd_refresh(repo, SPEC) == 0
    assert cli.cmd_check(repo, SPEC) == 0
    target = repo / cli.ENDPOINTS_PAGE
    target.write_text(target.read_text() + "\nhand edit\n")
    assert cli.cmd_check(repo, SPEC) == 1
    assert cli.cmd_refresh(repo, SPEC) == 0
    assert cli.cmd_check(repo, SPEC) == 0


def test_check_drifts_when_spec_changes(tmp_path):
    repo = make_repo(tmp_path, "repo", "golang.openapi.json")
    assert cli.cmd_refresh(repo, SPEC) == 0
    spec = repo / SPEC
    data = spec.read_bytes()
    data = data.replace(b"List Contents", b"List Contents (changed)")
    spec.write_bytes(data)
    assert cli.cmd_check(repo, SPEC) == 1


def test_init_scaffolds_then_is_idempotent(tmp_path):
    repo = make_repo(tmp_path, "repo", "golang.openapi.json")
    assert cli.cmd_init(repo, SPEC, False, "/tmp/kit-home") == 0
    for rel in (
        "docs/index.md",
        "docs/tutorials/index.md",
        "docs/guides/index.md",
        "docs/explanation/index.md",
        "docs/references/index.md",
        "zensical.toml",
        ".github/workflows/docs.yml",
        *generated_rels(),
    ):
        assert (repo / rel).is_file(), rel
    assert (repo / ".gitignore").exists()
    ign = (repo / ".gitignore").read_text()
    assert "site/" in ign and ".cache/" in ign
    cfg = tomllib.loads((repo / "zensical.toml").read_text())
    assert cfg["project"]["site_name"] == "golang-api-playground"
    assert cfg["project"]["nav"][0] == {"Home": "index.md"}
    mise = (repo / ".mise.toml").read_text()
    assert 'docs_kit = "/tmp/kit-home"' in mise
    assert 'DOCS_KIT = "{{ vars.docs_kit }}"' in mise
    assert 'includes = ["{{ vars.docs_kit }}/shared/mise/docs.toml"]' in mise
    assert 'run = "go run' not in mise  # no task bodies duplicated here
    assert 'uv = "latest"' in mise
    before = (repo / ".mise.toml").read_bytes()
    assert cli.cmd_init(repo, SPEC, False, "/tmp/kit-home") == 0  # repair no-op
    assert (repo / ".mise.toml").read_bytes() == before
    assert cli.cmd_init(repo, SPEC, True, "/tmp/kit-home") == 0
    assert (repo / ".mise.toml").read_bytes() == before


def test_init_repairs_deleted_tasks_block(tmp_path):
    repo = make_repo(tmp_path, "repo", "golang.openapi.json")
    assert cli.cmd_init(repo, SPEC, False, "/tmp/kit-home") == 0
    mise_path = repo / ".mise.toml"
    mise_path.write_text(
        mise_path.read_text().split("### docs")[0].rstrip() + "\n"
    )  # user deleted the integration block on purpose
    assert "docs_kit" not in mise_path.read_text()
    assert cli.cmd_init(repo, SPEC, False, "/tmp/kit-home") == 0
    mise = mise_path.read_text()
    assert "docs_kit" in mise and "task_config" in mise
    assert cli.cmd_check(repo, SPEC) == 0


def test_init_migrates_old_duplicated_block(tmp_path):
    repo = make_repo(tmp_path, "repo", "golang.openapi.json")
    assert cli.cmd_init(repo, SPEC, False, "/tmp/kit-home") == 0
    (repo / ".mise.toml").write_text(
        '[tasks.dev]\nrun = "true"\n\n'
        "### docs (block generated by docs-kit init; delete to remove) ###\n"
        '[env]\nDOCS_KIT = "/old/path"\n\n'
        '[tasks."docs:refresh"]\nrun = "echo old"\n'
        '[tasks."docs:check"]\nrun = "echo old"\n'
    )
    assert cli.cmd_init(repo, SPEC, False, "/tmp/kit-home") == 0
    mise = (repo / ".mise.toml").read_text()
    assert "docs_kit" in mise and "task_config" in mise
    assert 'run = "echo old"' not in mise          # old block replaced
    assert '[tasks.dev]' in mise                    # foreign tasks preserved


def test_init_migration_refused_with_foreign_tasks_below(tmp_path):
    repo = make_repo(tmp_path, "repo", "golang.openapi.json")
    assert cli.cmd_init(repo, SPEC, False, "/tmp/kit-home") == 0
    (repo / ".mise.toml").write_text(
        "### docs (block generated by docs-kit init; delete to remove) ###\n"
        '[tasks."docs:refresh"]\nrun = "echo old"\n\n'
        '[tasks."mine"]\nrun = "mine"\n'
    )
    assert cli.cmd_init(repo, SPEC, False, "/tmp/kit-home") == 0
    assert '[tasks."mine"]' in (repo / ".mise.toml").read_text()
    assert "docs_kit" not in (repo / ".mise.toml").read_text()  # refused, untouched


def test_init_refuses_hand_edits(tmp_path):
    repo = make_repo(tmp_path, "repo", "golang.openapi.json")
    assert cli.cmd_init(repo, SPEC, False, "/tmp/kit-home") == 0
    (repo / "zensical.toml").write_text("[project]\nsite_name = 'mine'\n")
    with pytest.raises(SystemExit):
        cli.cmd_init(repo, SPEC, False, "/tmp/kit-home")
    assert (repo / "zensical.toml").read_text().startswith("[project]")  # untouched
    assert cli.cmd_init(repo, SPEC, True, "/tmp/kit-home") == 0
    assert "golang-api-playground" in (repo / "zensical.toml").read_text()
    drifted = repo / cli.ENDPOINTS_PAGE
    drifted.write_text(drifted.read_text() + "\ndrift\n")
    with pytest.raises(SystemExit):
        cli.cmd_init(repo, SPEC, False, "/tmp/kit-home")
    assert cli.cmd_refresh(repo, SPEC) == 0  # generated files are refresh's job
    assert cli.cmd_init(repo, SPEC, False, "/tmp/kit-home") == 0


def test_init_merges_existing_mise_tables(tmp_path):
    repo = make_repo(tmp_path, "repo", "golang.openapi.json")
    (repo / ".mise.toml").write_text('[env]\nFOO = "1"\n\n[tools]\nrestish = "latest"\n')
    assert cli.cmd_init(repo, SPEC, False, "/tmp/kit-home") == 0
    cfg = tomllib.loads((repo / ".mise.toml").read_text())
    assert cfg["tools"]["uv"] == "latest"
    assert cfg["tools"]["restish"] == "latest"
    assert cfg["env"]["FOO"] == "1"
    assert cfg["env"]["DOCS_KIT"] == "{{ vars.docs_kit }}"  # templated at use, not write
    assert cfg["vars"]["docs_kit"] == "/tmp/kit-home"
    assert cfg["task_config"]["includes"] == [
        "{{ vars.docs_kit }}/shared/mise/docs.toml"
    ]
    assert (repo / ".mise.toml").read_text().count("[env]") == 1


def test_init_requires_spec(tmp_path):
    repo = tmp_path / "repo"
    repo.mkdir()
    with pytest.raises(SystemExit):
        cli.cmd_init(repo, SPEC, False, "/tmp/kit-home")
