"""Tests for shared/mise/usage-spec.py (the committed-KDL merge helper)."""

from __future__ import annotations

import importlib.util
import textwrap
from enum import Enum
from pathlib import Path
from typing import Annotated

import pytest
import typer

KIT = Path(__file__).resolve().parents[1]
HELPER = KIT / "shared/mise/usage-spec.py"

_spec = importlib.util.spec_from_file_location("usage_spec", HELPER)
usage_spec = importlib.util.module_from_spec(_spec)
assert _spec.loader is not None
_spec.loader.exec_module(usage_spec)


# --- generated-core shapes (byte-exact fixtures from real typer_usage runs) ---

FLAT_CORE = """\
// @generated by usage-spec-typer from Typer metadata
name stash-watcher
bin stash-watcher
about "Monitor Bitbucket Server activity."
flag "-p --project" help="Bitbucket project key." {
    arg <PROJECT>
}
flag --no-verify help="Disable TLS verification."
"""

TREE_CORE = """\
// @generated by usage-spec-typer from Typer metadata
name probe
bin probe
about "Probe CLI."
long_about "Probe CLI."
cmd main help="Do the thing." {
    flag "-p --project" help="Repeatable, comma-list." var=#true default="[]" {
        arg <PROJECT>
    }
    flag "-s --sort" help="Sort order." {
        arg <SORT> {
            choices activity name
        }
    }
}
cmd list subcommand_required=#true help="Sub group." {
    cmd things help="List things." {
        flag "-p --project" help="Repeatable project." var=#true default="[]" {
            arg <PROJECT>
        }
    }
}
"""

ROOT_EXTRA = """\
config {
    prop "token" type="string" help="API token" {
        env "STASH_TOKEN"
    }
}

exit_code 0 "table printed"
exit_code 1 "API or configuration failure"
"""


def test_no_extra_strips_banner_and_is_idempotent():
    once = usage_spec.merge(FLAT_CORE, None)
    again = usage_spec.merge(FLAT_CORE, None)
    assert once == again
    assert not once.startswith("//")
    assert once == "\n".join(FLAT_CORE.split("\n")[1:]).rstrip("\n") + "\n"
    assert "no-verify" in once


def test_root_extra_nodes_appended():
    merged = usage_spec.merge(FLAT_CORE, ROOT_EXTRA)
    assert "config {" in merged
    assert "exit_code 0" in merged
    # appended, not spliced: core flags stay untouched
    core_part, extra_part = merged.split("config {", 1)
    assert 'flag "-p --project"' in core_part
    assert "exit_code 1" in extra_part


def test_cmd_body_splice_keeps_generated_indent():
    extra = textwrap.dedent(
        """\
        cmd main {
            exit_code 0 "ok"
        }
        """
    )
    merged = usage_spec.merge(TREE_CORE, extra)
    lines = merged.split("\n")
    # the generated block keeps its 4-space body; the spliced statement matches
    idx = merged.find('flag "-p --project"')
    flag_indent = merged[:idx].rfind("\n")
    assert merged[flag_indent + 1 : flag_indent + 5] == "    "
    exit_line = next(ln for ln in lines if "exit_code 0" in ln and ln.strip())
    assert len(exit_line) - len(exit_line.lstrip()) == 4
    # spliced after the generated statements inside the same block
    assert merged.index('flag "-s --sort"') < merged.index("exit_code 0")


def test_nested_cmd_paths_splice_into_their_own_blocks():
    extra = textwrap.dedent(
        """\
        cmd list {
            cmd things {
                exit_code 0 "listed"
            }
            exit_code 2 "remote failure"
        }
        """
    )
    merged = usage_spec.merge(TREE_CORE, extra)
    lines = merged.split("\n")
    things_line = next(i for i, ln in enumerate(lines) if "cmd things" in ln)
    things_indent = len(lines[things_line]) - len(lines[things_line].lstrip())
    listed_line = next(i for i, ln in enumerate(lines) if "exit_code 0" in ln)
    remote_line = next(i for i, ln in enumerate(lines) if "exit_code 2" in ln)
    # the `}` at the CMD's own indentation (not a nested statement closer)
    close_things_line = next(
        i
        for i in range(things_line, len(lines))
        if lines[i].strip() == "}"
        and len(lines[i]) - len(lines[i].lstrip()) == things_indent
    )
    assert things_line < listed_line < close_things_line
    assert (
        close_things_line < remote_line
    )  # group-level node sits after the nested block
    assert (
        len(lines[listed_line]) - len(lines[listed_line].lstrip()) == things_indent + 4
    )
    assert len(lines[remote_line]) - len(lines[remote_line].lstrip()) == 4


def test_merged_output_is_stable_across_runs():
    extra = ROOT_EXTRA + '\ncmd main {\n    exit_code 3 "guard refused"\n}\n'
    assert usage_spec.merge(TREE_CORE, extra) == usage_spec.merge(TREE_CORE, extra)


def test_missing_cmd_path_fails_the_merge():
    extra = 'cmd gone {\n    exit_code 0 "x"\n}\n'
    with pytest.raises(SystemExit, match="no such command"):
        usage_spec.merge(TREE_CORE, extra)


def test_duplicate_root_config_fails():
    core_with_config = TREE_CORE.replace(
        "cmd main", 'config {\n    prop "jobs" type="int"\n}\ncmd main'
    )
    with pytest.raises(SystemExit, match="config"):
        usage_spec.merge(core_with_config, 'config {\n    prop "x" type="int"\n}\n')


def test_unbalanced_extra_block_fails():
    with pytest.raises(SystemExit, match="unterminated"):
        usage_spec.merge(TREE_CORE, 'cmd main {\n    exit_code 0 "x"\n')


def test_multiline_triple_quoted_extra_node_survives_validation():
    extra = (
        'exit_code 0 "ok"\n'
        'example """\n'
        "mise run stash-watcher    # table of the default project\n"
        "uv run stash-watcher --sort name # {brace} and quote '\"' survive\n"
        '"""\n'
    )
    merged = usage_spec.merge(FLAT_CORE, extra)
    assert 'example """' in merged
    assert "uv run stash-watcher --sort name" in merged


def test_empty_core_fails():
    with pytest.raises(SystemExit, match="empty"):
        usage_spec.merge("// banner only\n", None)


# --- end-to-end through --typer + --out (task shape) -------------------------


class _Sorter(str, Enum):
    activity = "activity"
    name = "name"


_app = typer.Typer(help="E2E CLI.")


@_app.command()
def probe_main(
    sort: Annotated[
        _Sorter, typer.Option("--sort", "-s", help="Sort.")
    ] = _Sorter.activity,
    repeat: Annotated[  # typer idiom for repeatable options: list + [] default
        list[str], typer.Option("--tag", "-t", help="Repeatable.")
    ] = [],  # noqa: B006
) -> None:
    """Probe."""


@pytest.fixture()
def toy_app(monkeypatch):
    usage_spec.load_app = lambda _spec: _app
    return _app


def test_main_writes_banner_and_merge(tmp_path, capsys, toy_app):
    extra = tmp_path / "toy.usage.extra.kdl"
    extra.write_text('exit_code 5 "boom"\n')
    out = tmp_path / "cli/toy.usage.kdl"
    rc = usage_spec.main(
        [
            "--typer",
            "irrelevant:app",
            "--bin",
            "toy",
            "--extra",
            str(extra),
            "--out",
            str(out),
        ]
    )
    assert rc == 0
    text = out.read_text()
    assert text.startswith(usage_spec.BANNER + "\n")
    assert "exit_code 5" in text
    # var=#true and choices come through unchanged from the exporter
    assert "var=#true" in text
    assert "choices activity name" in text
    # idempotent --out
    capsys.readouterr()
    assert (
        usage_spec.main(
            [
                "--typer",
                "irrelevant:app",
                "--bin",
                "toy",
                "--extra",
                str(extra),
                "--out",
                str(out),
            ]
        )
        == 0
    )
    assert "unchanged" in capsys.readouterr().out


def test_main_kdl_stdin_path(tmp_path, capsys):
    core = tmp_path / "core.kdl"
    core.write_text(FLAT_CORE)
    out = tmp_path / "cli/stash-watcher.usage.kdl"
    import io
    import sys as _sys

    real_stdin, _sys.stdin = _sys.stdin, io.StringIO(core.read_text(encoding="utf-8"))
    try:
        rc = usage_spec.main(
            ["--kdl-stdin", "--bin", "stash-watcher", "--out", str(out)]
        )
    finally:
        _sys.stdin = real_stdin
    assert rc == 0
    assert out.read_text().startswith(usage_spec.BANNER)


def test_multi_value_default_brackets_stripped():
    core = 'flag "-p --project" var=#true default="[]" {\n    arg <P>\n}\n'
    merged = usage_spec.merge(core, None)
    assert 'default="[]"' not in merged
    assert "var=#true" in merged


def test_missing_dependency_message(capsys):
    import builtins

    real_import = builtins.__import__

    def _block_typer_usage(name, *args, **kwargs):
        if name == "typer_usage":
            raise ModuleNotFoundError(name)
        return real_import(name, *args, **kwargs)

    builtins.__import__ = _block_typer_usage
    try:
        with pytest.raises(SystemExit) as exc:
            usage_spec.main(
                ["--typer", "docs_kit:nothing", "--bin", "toy", "--out", "/tmp/never"]
            )
    finally:
        builtins.__import__ = real_import
    assert "usage-spec-typer" in str(exc.value)
