from __future__ import annotations

import io
import os
import re
import shutil
import socket
import subprocess
import sys
import tomllib
import types
from pathlib import Path
from typing import Annotated

import pytest
import typer

from docs_kit import cli, detect, glue, layout, serve, shim, usage_spec

FIXTURES = Path(__file__).parent / "fixtures"
KIT = Path(__file__).resolve().parents[1]
SPEC = "openapi.json"

USAGE_STUB = (
    '#!/usr/bin/env python3\n"""Deterministic stand-in for the usage binary (tests only)."""'
    + """
import hashlib
import sys


def main() -> int:
    a = sys.argv
    if len(a) >= 3 and a[1] == "lint":
        with open(a[2], encoding="utf-8", errors="replace") as f:
            return 1 if "LINTFAIL" in f.read() else 0
    if a[1:3] == ["generate", "markdown"] and "-f" in a:
        kdl = a[a.index("-f") + 1]
        with open(kdl, "rb") as f:
            digest = hashlib.sha256(f.read()).hexdigest()[:12]
        sys.stdout.write(
            "<!-- @generated by usage-cli from usage spec -->\\n"
            f"fake page for {kdl} {digest}\\n"
        )
        return 0
    return 2


sys.exit(main())
"""
)


@pytest.fixture(autouse=True)
def _fake_usage(tmp_path, monkeypatch):
    """Page rendering must never depend on whether a real `usage` binary is
    installed on the dev machine - every test sees the same stub (PATH-first)."""
    stub_dir = tmp_path / "_fakebin"
    stub_dir.mkdir(exist_ok=True)
    stub = stub_dir / "usage"
    stub.write_text(USAGE_STUB, encoding="utf-8")
    stub.chmod(0o755)
    monkeypatch.setenv(
        "PATH", os.pathsep.join([str(stub_dir), *os.environ["PATH"].split(os.pathsep)])
    )


@pytest.fixture(autouse=True)
def _skip_layer_pull(monkeypatch):
    """init never shells out to git in tests (the file:// tests opt back in)."""
    monkeypatch.setenv("DOCS_KIT_SKIP_PULL", "1")


def make_repo(base: Path, name: str, fixture: str, github: bool = True) -> Path:
    repo = base / name
    repo.mkdir(parents=True, exist_ok=True)
    shutil.copy(FIXTURES / fixture, repo / SPEC)
    if github:
        # the workflow file is generated only where it can run: a clone with
        # a GitHub remote (or CI env var); the dir marker stands in for both
        (repo / ".github" / "workflows").mkdir(parents=True)
    return repo


def strip_spec_prose(text: str) -> str:
    keep = (
        "Canonical specification:",
        "<title>",
    )
    return "\n".join(
        l for l in text.splitlines() if not any(l.startswith(k) for k in keep)
    )


def generated_rels():
    return (
        layout.VENDORED_SPEC,
        layout.SWAGGER_PAGE,
        layout.API_PAGE,
        layout.ENDPOINTS_PAGE,
        layout.WORKFLOW,
    )


def test_both_specs_render_identical_pages(tmp_path):
    go = make_repo(tmp_path, "go", "golang.openapi.json")
    py = make_repo(tmp_path, "py", "python.openapi.json")
    assert cli.cmd_refresh(go, SPEC) == 0
    assert cli.cmd_refresh(py, SPEC) == 0
    for rel in (layout.ENDPOINTS_PAGE, layout.API_PAGE, layout.SWAGGER_PAGE):
        assert strip_spec_prose((go / rel).read_text()) == strip_spec_prose(
            (py / rel).read_text()
        ), rel
    assert (go / layout.VENDORED_SPEC).read_bytes() == (go / SPEC).read_bytes()


def test_refresh_is_byte_stable(tmp_path):
    repo = make_repo(tmp_path, "repo", "golang.openapi.json")
    assert cli.cmd_refresh(repo, SPEC) == 0
    before = {rel: (repo / rel).read_bytes() for rel in generated_rels()}
    assert cli.cmd_refresh(repo, SPEC) == 0
    after = {rel: (repo / rel).read_bytes() for rel in generated_rels()}
    assert before == after


def test_check_detects_stale_and_missing(tmp_path):
    repo = make_repo(tmp_path, "repo", "golang.openapi.json")
    assert cli.cmd_check(repo, SPEC) == 1  # nothing generated yet
    assert cli.cmd_refresh(repo, SPEC) == 0
    assert cli.cmd_check(repo, SPEC) == 0
    target = repo / layout.ENDPOINTS_PAGE
    target.write_text(target.read_text() + "\nhand edit\n")
    assert cli.cmd_check(repo, SPEC) == 1
    assert cli.cmd_refresh(repo, SPEC) == 0
    assert cli.cmd_check(repo, SPEC) == 0


def test_check_drifts_when_spec_changes(tmp_path):
    repo = make_repo(tmp_path, "repo", "golang.openapi.json")
    assert cli.cmd_refresh(repo, SPEC) == 0
    spec = repo / SPEC
    data = spec.read_bytes()
    data = data.replace(b"List Contents", b"List Contents (changed)")
    spec.write_bytes(data)
    assert cli.cmd_check(repo, SPEC) == 1


def test_workflow_pin_is_stamped_and_checked(tmp_path):
    repo = make_repo(tmp_path, "repo", "golang.openapi.json")
    assert cli.cmd_refresh(repo, SPEC) == 0
    wf = repo / layout.WORKFLOW
    text = wf.read_text()
    assert f"ref: v{cli.__version__}" in text
    assert text.count(f"ref: v{cli.__version__}") == 2  # BOTH jobs, one render
    assert "__KIT_VERSION__" not in text
    assert '"{{ vars.docs_kit }}"' in text  # GHA braces survive the stamping
    # CI recreates the gitignored mise.local.toml opt-in keys
    assert "mise.local.toml" in text
    # release pipelines call the workflow (a GITHUB_TOKEN `on: release` never fires)
    assert "workflow_call" in text
    # hand tweaks or a hand-bumped ref are drift, not ownership
    wf.write_text(text.replace(f"ref: v{cli.__version__}", "ref: v9.9.9", 1))
    assert cli.cmd_check(repo, SPEC) == 1
    assert cli.cmd_refresh(repo, SPEC) == 0  # refresh re-stamps, don't hand-edit
    assert cli.cmd_check(repo, SPEC) == 0


def test_init_scaffolds_without_touching_mise(tmp_path, capsys):
    repo = make_repo(tmp_path, "repo", "golang.openapi.json")
    assert cli.cmd_init(repo, SPEC, False, ".docs-kit", use_mise=True) == 0
    for rel in (
        "docs/index.md",
        "docs/tutorials/index.md",
        "docs/guides/index.md",
        "docs/explanation/index.md",
        "docs/references/index.md",
        "zensical.toml",
        *generated_rels(),
    ):
        assert (repo / rel).is_file(), rel
    cfg = tomllib.loads((repo / "zensical.toml").read_text())
    assert cfg["project"]["site_name"] == "golang-api-playground"
    assert cfg["project"]["nav"][0] == {"Home": "index.md"}
    # the user's mise configs are never written, and no block template file
    # exists - .docs-kit/ is reserved for the pulled task layer only
    assert not (repo / ".mise.toml").exists()
    assert not (repo / "mise.local.toml").exists()
    assert not (repo / ".docs-kit").exists()  # pull skipped (DOCS_KIT_SKIP_PULL)
    ign = (repo / ".gitignore").read_text().split()
    assert {"site/", ".cache/", ".docs-kit/", "mise.local.toml"} <= set(ign)
    out = capsys.readouterr().out
    block = shim.mise_block(".docs-kit")
    assert tomllib.loads(block)["task_config"]["includes"] == [
        "{{ vars.docs_kit }}/shared/mise/docs.toml"
    ]
    assert block.rstrip("\n") in out  # the exact block body is printed, comment-free...
    assert not any(ln.lstrip().startswith("#") for ln in block.splitlines())
    assert (
        "copy-paste" in out
    )  # ...for manual copy, phrased as "a mise config", never as
    assert "auto-loads" not in out  # mise.local.toml heredoc wiring (old message shape)
    before = (repo / ".gitignore").read_bytes()
    assert (
        cli.cmd_init(repo, SPEC, False, ".docs-kit", use_mise=True) == 0
    )  # repair no-op
    assert before == (repo / ".gitignore").read_bytes()
    assert (
        cli.cmd_init(repo, SPEC, True, ".docs-kit", use_mise=True) == 0
    )  # --force changes nothing either
    assert before == (repo / ".gitignore").read_bytes()
    assert not (repo / ".mise.toml").exists()
    assert not (repo / ".docs-kit").exists()


def test_init_default_kit_home_is_the_shim(tmp_path, monkeypatch):
    # the CLI may live in a checkout; the default must STILL be the pullable
    # shim so `uv run --project <kit> docs-kit init` wires the task layer
    monkeypatch.delenv("DOCS_KIT", raising=False)
    assert shim.default_kit_home() == ".docs-kit"


def test_init_checkout_mode_records_absolute_kit_path(tmp_path, capsys, monkeypatch):
    repo = make_repo(tmp_path, "repo", "golang.openapi.json")

    def _boom(*args, **kwargs):
        raise AssertionError("checkout mode must never sync a task layer")

    monkeypatch.setattr(shim, "pull_tasks", _boom)
    monkeypatch.delenv("DOCS_KIT_SKIP_PULL", raising=False)
    assert cli.cmd_init(repo, SPEC, False, "/abs/docs-kit-checkout", use_mise=True) == 0
    capsys.readouterr()
    assert (repo / "mise.local.toml").read_text() == shim.mise_block(
        "/abs/docs-kit-checkout"
    )
    assert (
        'docs_kit = "/abs/docs-kit-checkout"' in (repo / "mise.local.toml").read_text()
    )
    assert not (repo / ".mise.toml").exists()
    assert not (repo / ".docs-kit").exists()  # checkout mode creates nothing else


def test_init_never_rewrites_mise_toml(tmp_path, capsys):
    repo = make_repo(tmp_path, "repo", "golang.openapi.json")
    mise = repo / ".mise.toml"
    mise.write_text(
        '[vars]\ndocs_kit = "/tmp/old-kit"\n\n[tasks.mine]\nrun = "go run ."\n'
    )
    before = mise.read_bytes()
    assert cli.cmd_init(repo, SPEC, False, ".docs-kit", use_mise=True) == 0
    assert "OUTDATED" in capsys.readouterr().out  # stale keys: replace hint only
    assert mise.read_bytes() == before


def test_opt_in_hints_on_existing_mise_local(tmp_path, capsys):
    repo = make_repo(tmp_path, "repo", "golang.openapi.json")
    assert cli.cmd_init(repo, SPEC, False, ".docs-kit", use_mise=True) == 0
    block = shim.mise_block(".docs-kit")
    # consumer pasted the printed heredoc (their own config above it)
    before = '[tools]\nuv = "latest"\n\n'
    (repo / "mise.local.toml").write_text(before + block)
    capsys.readouterr()
    assert cli.cmd_init(repo, SPEC, False, ".docs-kit", use_mise=True) == 0
    out = capsys.readouterr().out
    assert "copy-paste" not in out and "OUTDATED" not in out  # opt-in detected
    assert (repo / "mise.local.toml").read_text() == before + block  # untouched
    # an old-shape block (stale docs_kit value) asks for a replace
    old = '# docs-kit integration (generated by `docs-kit init --docs-kit .docs-kit`)\n[vars]\ndocs_kit = ".old"\n'
    (repo / "mise.local.toml").write_text(old)
    assert cli.cmd_init(repo, SPEC, False, ".docs-kit", use_mise=True) == 0
    assert "OUTDATED or hand-edited" in capsys.readouterr().out
    assert (repo / "mise.local.toml").read_text() == old  # still untouched


def _pull_ok(monkeypatch):
    """Make init's shim sync succeed and actually run (autouse fixture skips it)."""
    monkeypatch.delenv("DOCS_KIT_SKIP_PULL", raising=False)

    def fake(root, shim, version=cli.__version__):
        (root / shim).mkdir(parents=True, exist_ok=True)
        return f"v{version}"

    monkeypatch.setattr(shim, "pull_tasks", fake)


def test_init_creates_mise_local_when_absent(tmp_path, capsys, monkeypatch):
    repo = make_repo(tmp_path, "repo", "golang.openapi.json")
    _pull_ok(monkeypatch)
    assert cli.cmd_init(repo, SPEC, False, ".docs-kit", use_mise=True) == 0
    out = capsys.readouterr().out
    assert (repo / "mise.local.toml").read_text() == shim.mise_block(".docs-kit")
    assert (
        tomllib.loads((repo / "mise.local.toml").read_text())["vars"]["docs_kit"]
        == ".docs-kit"
    )
    assert "created" in out and "copy-paste" not in out and "OUTDATED" not in out
    before = (repo / "mise.local.toml").read_bytes()
    assert (
        cli.cmd_init(repo, SPEC, False, ".docs-kit", use_mise=True) == 0
    )  # repair no-op
    assert (repo / "mise.local.toml").read_bytes() == before
    assert "copy-paste" not in capsys.readouterr().out


def test_init_appends_keys_to_simple_mise_local(tmp_path, capsys, monkeypatch):
    repo = make_repo(tmp_path, "repo", "golang.openapi.json")
    (repo / "mise.local.toml").write_text('[tools]\nuv = "latest"\n')
    _pull_ok(monkeypatch)
    assert cli.cmd_init(repo, SPEC, False, ".docs-kit", use_mise=True) == 0
    out = capsys.readouterr().out
    assert "appended" in out and "copy-paste" not in out
    txt = (repo / "mise.local.toml").read_text()
    assert txt.startswith('[tools]\nuv = "latest"')
    assert tomllib.loads(txt)["vars"]["docs_kit"] == ".docs-kit"
    before = (repo / "mise.local.toml").read_bytes()
    assert (
        cli.cmd_init(repo, SPEC, False, ".docs-kit", use_mise=True) == 0
    )  # detected, untouched
    assert (repo / "mise.local.toml").read_bytes() == before
    assert "appended" not in capsys.readouterr().out


def test_init_refuses_risky_mise_local_merge(tmp_path, capsys, monkeypatch):
    repo = make_repo(tmp_path, "repo", "golang.openapi.json")
    (repo / "mise.local.toml").write_text(
        '[vars]\nMY_VAR = "1"\n'
    )  # would duplicate [vars]
    _pull_ok(monkeypatch)
    assert cli.cmd_init(repo, SPEC, False, ".docs-kit", use_mise=True) == 0
    out = capsys.readouterr().out
    assert "copy-paste" in out  # manual paste/merge guidance, file untouched
    assert (repo / "mise.local.toml").read_text() == '[vars]\nMY_VAR = "1"\n'


def test_init_writes_no_mise_local_when_pull_fails(tmp_path, capsys, monkeypatch):
    repo = make_repo(tmp_path, "repo", "golang.openapi.json")
    monkeypatch.delenv("DOCS_KIT_SKIP_PULL", raising=False)

    def _fail(root, shim, version=cli.__version__):
        raise RuntimeError("no payload at v9.9.9")

    monkeypatch.setattr(shim, "pull_tasks", _fail)
    assert cli.cmd_init(repo, SPEC, False, ".docs-kit", use_mise=True) == 0
    out = capsys.readouterr().out
    assert "WARNING" in out
    assert not (repo / "mise.local.toml").exists()  # broken include never wired
    assert "copy-paste" in out  # block printed for a later manual opt-in


def test_init_without_mise(tmp_path, capsys):
    repo = make_repo(tmp_path, "repo", "golang.openapi.json")
    mise = repo / ".mise.toml"
    mise.write_text('[tools]\nuv = "latest"\n\ndocs_kit = ".docs-kit"\n')
    before = mise.read_bytes()
    assert cli.cmd_init(repo, SPEC, False, ".docs-kit", use_mise=False) == 0
    out = capsys.readouterr().out
    assert "--with-mise" in out
    assert "cleanup" not in out and "copy-paste" not in out and "docs_kit" not in out
    assert not (repo / ".docs-kit").exists()  # no dir, no template, no layer
    assert not (repo / "mise.local.toml").exists()
    ign = (repo / ".gitignore").read_text().split()
    assert "site/" in ign and ".cache/" in ign
    assert ".docs-kit/" not in ign and "mise.local.toml" not in ign
    for rel in (
        "docs/index.md",
        "docs/tutorials/index.md",
        "docs/guides/index.md",
        "docs/explanation/index.md",
        "docs/references/index.md",
        "zensical.toml",
        *generated_rels(),
    ):
        assert (repo / rel).is_file(), rel
    assert mise.read_bytes() == before


def test_shared_docs_toml_ships_pull_tasks():
    tasks = tomllib.loads((KIT / "shared/mise/docs.toml").read_text())
    assert {
        "docs:init",
        "docs:refresh",
        "docs:build",
        "docs:serve",
        "docs:check",
        "docs:pull-tasks",
    } <= set(tasks)
    run = tasks["docs:pull-tasks"]["run"]
    assert 'exec sh "$shim/shared/mise/kit-sync" "$shim"' in run  # the engine
    assert (
        "nothing to pull" in run
    )  # checkout installs ($DOCS_KIT absolute): exit-0 guard


def make_tagged_kit(base: Path) -> Path:
    """Throwaway kit repo: v0.1.0 predates the payload, v9.9.9 ships shared/mise.

    The real clone carries no release tags until release-please cuts one,
    so pull tests must never depend on tags of the repo they live in.
    """
    kit = base / "kit"
    kit.mkdir()

    def git(*args):
        subprocess.run(
            ("git", *args),
            cwd=kit,
            check=True,
            capture_output=True,
            env={
                **os.environ,
                "GIT_AUTHOR_NAME": "t",
                "GIT_AUTHOR_EMAIL": "t@t",
                "GIT_COMMITTER_NAME": "t",
                "GIT_COMMITTER_EMAIL": "t@t",
            },
        )

    (kit / "README.md").write_text("kit before the payload\n")
    git("init", "-q", "-b", "main", ".")
    git("add", "-A")
    git("commit", "-q", "-m", "pre-payload")
    git("tag", "v0.1.0")
    (kit / "shared/mise").mkdir(parents=True)
    shutil.copy(KIT / "shared/mise/kit-sync", kit / "shared/mise/kit-sync")
    (kit / "shared/mise/docs.toml").write_text('"docs:x" = { run = "true" }\n')
    git("add", "-A")
    git("commit", "-q", "-m", "task layer")
    git("tag", "v9.9.9")
    return kit


def test_pull_tasks_bootstraps_shim_in_place(tmp_path, monkeypatch):
    monkeypatch.setenv("DOCS_KIT_REPO", "file://" + str(make_tagged_kit(tmp_path)))
    repo = tmp_path / "consumer"
    shim_dir = repo / ".docs-kit"
    shim_dir.mkdir(parents=True)
    (shim_dir / "stray.txt").write_text("dir already existed without a checkout\n")
    assert shim.pull_tasks(repo, ".docs-kit", "9.9.9") == "v9.9.9"
    assert (
        shim_dir / "shared/mise/docs.toml"
    ).is_file()  # payload materialized around it
    assert not (shim_dir / "src").exists()  # sparse: only /shared/mise/
    assert "dir already existed" in (shim_dir / "stray.txt").read_text()
    assert shim.pull_tasks(repo, ".docs-kit", "9.9.9") == "v9.9.9"  # idempotent re-pin
    # a missing dir is also fine (pull creates it)
    repo2 = tmp_path / "consumer2"
    assert shim.pull_tasks(repo2, ".docs-kit", "9.9.9") == "v9.9.9"


def test_pull_tasks_refuses_tag_without_payload(tmp_path, monkeypatch):
    """v0.1.x tags predate shared/mise - pulling one must never wipe a layer."""
    monkeypatch.setenv("DOCS_KIT_REPO", "file://" + str(make_tagged_kit(tmp_path)))
    repo = tmp_path / "consumer"
    assert shim.pull_tasks(repo, ".docs-kit", "9.9.9") == "v9.9.9"
    with pytest.raises(RuntimeError, match="no task layer"):
        shim.pull_tasks(repo, ".docs-kit", "0.1.0")
    assert git_describe(repo / ".docs-kit") == "v9.9.9"  # layer untouched
    assert (repo / ".docs-kit/shared/mise/docs.toml").is_file()


def test_kit_sync_engine_pins_and_refuses_payloadless_tags(tmp_path, monkeypatch):
    """shared/mise/kit-sync is what `mise run docs:pull-tasks` executes."""
    monkeypatch.setenv("DOCS_KIT_REPO", "file://" + str(make_tagged_kit(tmp_path)))
    repo = tmp_path / "consumer"
    repo.mkdir()

    def sync(ver):
        return subprocess.run(
            ["sh", str(KIT / "shared/mise/kit-sync"), ".docs-kit", ver],
            cwd=repo,
            capture_output=True,
            text=True,
            check=False,
        )

    assert sync("9.9.9").returncode == 0
    assert (repo / ".docs-kit/shared/mise/docs.toml").is_file()
    assert sync("9.9.9").returncode == 0  # already pinned: fast exit
    assert sync("0.1.0").returncode == 3
    assert git_describe(repo / ".docs-kit") == "v9.9.9"


def git_describe(path):
    import subprocess

    return subprocess.run(
        ["git", "-C", str(path), "describe", "--tags", "--exact-match"],
        capture_output=True,
        text=True,
        check=False,
    ).stdout.strip()


def test_init_refuses_hand_edits(tmp_path):
    repo = make_repo(tmp_path, "repo", "golang.openapi.json")
    assert cli.cmd_init(repo, SPEC, False, ".docs-kit") == 0
    (repo / "zensical.toml").write_text("[project]\nsite_name = 'mine'\n")
    with pytest.raises(SystemExit):
        cli.cmd_init(repo, SPEC, False, ".docs-kit")
    assert (repo / "zensical.toml").read_text().startswith("[project]")  # untouched
    assert cli.cmd_init(repo, SPEC, True, ".docs-kit") == 0
    assert "golang-api-playground" in (repo / "zensical.toml").read_text()
    drifted = repo / layout.ENDPOINTS_PAGE
    drifted.write_text(drifted.read_text() + "\ndrift\n")
    with pytest.raises(SystemExit):
        cli.cmd_init(repo, SPEC, False, ".docs-kit")
    assert cli.cmd_refresh(repo, SPEC) == 0  # generated files are refresh's job
    assert cli.cmd_init(repo, SPEC, False, ".docs-kit") == 0


def test_init_requires_spec(tmp_path):
    repo = tmp_path / "repo"
    repo.mkdir()
    with pytest.raises(SystemExit):
        cli.cmd_init(repo, SPEC, False, ".docs-kit")


def _fake_server(monkeypatch):
    calls = []

    class _Done:
        returncode = 0

    monkeypatch.setattr(
        serve.subprocess, "run", lambda cmd, **kw: calls.append(cmd) or _Done()
    )
    return calls


def _served(addr):
    return [[sys.executable, "-m", "zensical", "serve", "--dev-addr", addr]]


def test_serve_pinned_via_flag(tmp_path, monkeypatch):
    monkeypatch.delenv("DOCS_PORT", raising=False)
    calls = _fake_server(monkeypatch)
    assert cli.main(["serve", str(tmp_path), "--port", "9998"]) == 0
    assert calls == _served("127.0.0.1:9998")


def test_serve_pinned_via_env(tmp_path, monkeypatch):
    monkeypatch.setenv("DOCS_PORT", "9997")
    calls = _fake_server(monkeypatch)
    assert cli.main(["serve", str(tmp_path)]) == 0
    assert calls == _served("127.0.0.1:9997")


def test_serve_leases_around_a_busy_preferred(tmp_path, monkeypatch):
    monkeypatch.delenv("DOCS_PORT", raising=False)
    monkeypatch.setenv("FREE_PORT_MIN", "8010")
    monkeypatch.setenv("FREE_PORT_MAX", "8015")
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as busy:
        busy.bind(("127.0.0.1", serve.DEFAULT_PORT))
        expected = next(p for p in range(8011, 8016) if serve.port_free(p, "127.0.0.1"))
        calls = _fake_server(monkeypatch)
        assert cli.main(["serve", str(tmp_path)]) == 0
    assert calls == _served(f"127.0.0.1:{expected}")


def test_build_runs_zensical_from_this_env(tmp_path, monkeypatch):
    calls = _fake_server(monkeypatch)
    assert cli.main(["build", str(tmp_path)]) == 0
    assert calls == [[sys.executable, "-m", "zensical", "build", "--clean"]]


# ---------------------------------------------------------------------------
# autodetection: API / CLI / both / neither, the GitHub gate and [tools] usage


TYPER_PYPROJECT = (
    '[project]\nname = "mytool"\nversion = "0.1.0"\n'
    'dependencies = ["typer>=0.12", "rich"]\n'
    '[project.scripts]\nmytool = "mytool.cli:app"\n\n'
    '[dependency-groups]\ndev = ["usage-spec-typer>=1.2.1"]\n'
)


def make_cli_repo(
    base: Path, name: str, *, typer: bool = True, kdl: tuple = ()
) -> Path:
    repo = base / name
    repo.mkdir(parents=True)
    if typer:
        (repo / "pyproject.toml").write_text(TYPER_PYPROJECT)
    for bin_name in kdl:
        d = repo / "cli"
        d.mkdir(exist_ok=True)
        (d / f"{bin_name}.usage.kdl").write_text(f'cmd "{bin_name}" {{\n}}\n')
        (d / f"{bin_name}.usage.extra.kdl").write_text("# curated extras\n")
    return repo


def test_detect_cli_only_typer(tmp_path):
    repo = make_cli_repo(tmp_path, "tool")
    api, bins = detect.detect_pipelines(repo, SPEC, False, [])
    assert not api
    assert bins == {"mytool": {"recipe": "python", "app": "mytool.cli:app"}}


def test_detect_committed_kdl_and_ignores_extras(tmp_path):
    repo = tmp_path / "repo"
    d = repo / "cli"
    d.mkdir(parents=True)
    (d / "tool.usage.kdl").write_text('cmd "tool" {}\n')
    (d / "tool.usage.extra.kdl").write_text("# curated\n")
    _, bins = detect.detect_pipelines(repo, SPEC, False, [])
    assert bins == {"tool": {"recipe": "kdl"}}


def test_detect_cobra_and_explicit_bins(tmp_path):
    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / "go.mod").write_text(
        "module github.com/acme/goodtool\n\ngithub.com/spf13/cobra v1.10.2\n"
    )
    _, bins = detect.detect_pipelines(repo, SPEC, False, ["other-cli"])
    assert bins["goodtool"]["recipe"] == "go"
    assert bins["other-cli"]["recipe"] == "unknown"


def test_no_api_no_cli_overrides(tmp_path):
    repo = make_repo(tmp_path, "both", "golang.openapi.json")
    (repo / "cli").mkdir()
    (repo / "cli" / "tool.usage.kdl").write_text('cmd "tool" {}\n')
    api, bins = detect.detect_pipelines(repo, SPEC, False, [])
    assert api and bins
    api, bins = detect.detect_pipelines(repo, SPEC, False, [], no_cli=True)
    assert api and bins == {}
    api, bins = detect.detect_pipelines(repo, SPEC, False, [], no_api=True)
    assert not api and bins


def test_init_cli_only_repo_end_to_end(tmp_path, monkeypatch):
    monkeypatch.delenv("GITHUB_REPOSITORY", raising=False)
    repo = make_cli_repo(tmp_path, "toolrepo")
    assert cli.cmd_init(repo, SPEC, False, "/abs/kit", use_mise=True) == 0
    zens = (repo / layout.ZENSICAL_CONFIG).read_text()
    assert "references/cli/mytool.md" in zens
    assert "references/cli-standard.md" in zens
    assert "references/api.md" not in zens
    assert (repo / layout.CLI_STANDARD_PAGE).is_file()
    assert "mytool" in (repo / layout.CLI_STANDARD_PAGE).read_text()
    assert not (repo / layout.API_PAGE).exists()
    assert not (repo / layout.WORKFLOW).exists()  # no github evidence anywhere
    # the CLI pipeline needs the usage binary -> the opt-in block pins it
    assert tomllib.loads((repo / "mise.local.toml").read_text())["tools"]["usage"]
    assert cli.cmd_refresh(repo, SPEC) == 0
    assert cli.cmd_check(repo, SPEC) == 0


def test_init_api_only_block_has_no_tools(tmp_path):
    repo = make_repo(tmp_path, "api", "golang.openapi.json")
    assert cli.cmd_init(repo, SPEC, False, "/abs/kit", use_mise=True) == 0
    block = tomllib.loads((repo / "mise.local.toml").read_text())
    assert "tools" not in block
    block2 = tomllib.loads(shim.mise_block("k", cli=True))
    assert block2["tools"]["usage"] == "latest"


def test_init_both_pipelines_scaffolds_everything(tmp_path):
    repo = make_repo(tmp_path, "both", "golang.openapi.json")
    (repo / "pyproject.toml").write_text(TYPER_PYPROJECT)
    assert cli.cmd_init(repo, SPEC, False, ".docs-kit") == 0
    for rel in generated_rels() + (layout.CLI_STANDARD_PAGE,):
        assert (repo / rel).is_file(), rel
    zens = (repo / layout.ZENSICAL_CONFIG).read_text()
    assert "references/endpoints.md" in zens and "references/cli/mytool.md" in zens


def test_init_neither_pipeline_refuses(tmp_path, monkeypatch):
    repo = tmp_path / "empty"
    repo.mkdir()
    (repo / "README.md").write_text("# nothing to document\n")
    # an Actions-like environment must not masquerade as a documentation
    # source: runners set GITHUB_REPOSITORY, and init has to refuse there too
    monkeypatch.setenv("GITHUB_REPOSITORY", "octo/empty-repo")
    with pytest.raises(SystemExit) as exc:
        cli.cmd_init(repo, SPEC, False, ".docs-kit")
    assert "no documentation source detected" in str(exc.value)


def test_workflow_only_when_github_detected(tmp_path, monkeypatch):
    monkeypatch.delenv("GITHUB_REPOSITORY", raising=False)
    repo = make_repo(tmp_path, "stashy", "golang.openapi.json", github=False)
    assert cli.cmd_init(repo, SPEC, False, ".docs-kit") == 0
    assert not (repo / layout.WORKFLOW).exists()
    assert cli.cmd_check(repo, SPEC) == 0  # check must not demand a workflow
    assert cli.cmd_refresh(repo, SPEC) == 0
    assert not (repo / layout.WORKFLOW).exists()


def test_github_detected_via_git_config(tmp_path, monkeypatch):
    monkeypatch.delenv("GITHUB_REPOSITORY", raising=False)
    repo = make_repo(tmp_path, "clone", "golang.openapi.json", github=False)
    (repo / ".git").mkdir()
    (repo / ".git" / "config").write_text(
        '[remote "origin"]\n\turl = git@github.com:acme/tool.git\n'
    )
    assert cli.cmd_refresh(repo, SPEC) == 0
    assert (repo / layout.WORKFLOW).is_file()
    (repo / ".git" / "config").write_text(
        '[remote "origin"]\n\turl = git@stash.ovh.net:~acme/tool.git\n'
    )
    (repo / layout.WORKFLOW).unlink()
    (repo / layout.WORKFLOW).parent.rmdir()
    (repo / ".github").rmdir()  # a leftover dir marker also says GitHub: remove both
    (repo / ".git" / "config").write_text(
        '[remote "origin"]\n\turl = git@stash.ovh.net:~acme/tool.git\n'
    )
    assert cli.cmd_refresh(repo, SPEC) == 0
    assert not (repo / layout.WORKFLOW).exists()  # never written, never removed


BASH_ONLY_EXPANSIONS = [
    # ${var/pat/rep} and ${var//pat/rep} - bash/zsh; dash and POSIX sh fail
    # with "Bad substitution" AT RUNTIME (-n does not catch them).
    re.compile(r"\$\{[A-Za-z_][A-Za-z0-9_]*(/[^}]*)?\}"),
    # ${var:offset:length} - bash substring; POSIX ${var:-x}/${var:+y}/... ok
    re.compile(r"\$\{[A-Za-z_][A-Za-z0-9_]*:[^}=\-+?]"),
]


def test_shared_mise_bodies_are_posix():
    """The mise task layer of consumers runs under their /bin/sh - on Ubuntu
    that is dash. Nothing else lints these TOML bodies (shellcheck does not
    read TOML), and dash only rejects ${var/pat/rep} at runtime, so gate both
    statically here and parse-check with dash when it exists."""
    tasks = tomllib.loads((KIT / "shared/mise/docs.toml").read_text(encoding="utf-8"))
    bodies = {
        name: spec["run"]
        for name, spec in tasks.items()
        if isinstance(spec, dict) and isinstance(spec.get("run"), str)
    }
    assert bodies
    for name, body in bodies.items():
        for pattern in BASH_ONLY_EXPANSIONS:
            match = pattern.search(body)
            assert match is None, f"{name}: bash-only expansion {match.group(0)}"
        dash = shutil.which("dash")
        if dash:
            result = subprocess.run(
                [dash, "-n", "-c", body],
                capture_output=True,
                text=True,
                check=False,
            )
            assert result.returncode == 0, (
                f"{name}: dash parse: {result.stderr.strip()}"
            )


# ---------------------------------------------------------------------------
# dependency mode: docs-kit spec / docs-kit render / committed mise glue


TOY_APP = typer.Typer(help="Toy CLI for dependency-mode tests.")


@TOY_APP.command()
def greet(
    name: Annotated[str, typer.Option(help="Who to greet.")] = "world",
) -> None:
    """Greet someone."""


def _fake_app_module(monkeypatch, name="mytool"):
    """Make `<pkg>.cli:app` importable in THIS venv (what dependency mode
    gets from `uv run docs-kit spec` living in the consumer's own environment)."""
    pkg = types.ModuleType(name)
    pkg.__path__ = []
    mod = types.ModuleType(f"{name}.cli")
    mod.app = TOY_APP
    monkeypatch.setitem(sys.modules, name, pkg)
    monkeypatch.setitem(sys.modules, f"{name}.cli", mod)


def test_spec_writes_contract_and_merges_extra(tmp_path, monkeypatch, capsys):
    repo = make_cli_repo(tmp_path, "toyrepo")
    _fake_app_module(monkeypatch)
    assert cli.cmd_spec(repo) == 0
    kdl = (repo / "cli/mytool.usage.kdl").read_text()
    assert kdl.startswith(usage_spec.BANNER)
    # a single-command Typer app flattens to root flags in the exporter
    assert "flag --name" in kdl and 'about "Toy CLI' in kdl
    capsys.readouterr()
    assert cli.cmd_spec(repo) == 0  # byte-stable: nothing rewritten
    assert "contract current" in capsys.readouterr().out
    (repo / "cli/mytool.usage.extra.kdl").write_text('exit_code 7 "guard"\n')
    assert cli.cmd_spec(repo) == 0
    assert 'exit_code 7 "guard"' in (repo / "cli/mytool.usage.kdl").read_text()


def test_spec_go_recipe_eats_piped_core(tmp_path, monkeypatch):
    repo = tmp_path / "goro"
    (repo / "cli").mkdir(parents=True)
    (repo / "go.mod").write_text(
        "module github.com/acme/probe\n\ngithub.com/spf13/cobra v1.10.2\n"
    )
    monkeypatch.setattr(
        sys, "stdin", io.StringIO('name probe\nbin probe\nabout "p."\n')
    )
    assert cli.cmd_spec(repo) == 0
    assert (repo / "cli/probe.usage.kdl").read_text().startswith(usage_spec.BANNER)


def test_spec_go_recipe_refuses_a_tty(tmp_path, monkeypatch):
    repo = tmp_path / "goro"
    (repo / "cli").mkdir(parents=True)
    (repo / "go.mod").write_text("module acme/probe\ngithub.com/spf13/cobra v1.10.2\n")

    class _TTY(io.StringIO):
        def isatty(self):
            return True

    monkeypatch.setattr(sys, "stdin", _TTY())
    with pytest.raises(SystemExit, match="usage-spec"):
        cli.cmd_spec(repo)


def test_refresh_respecs_python_contracts_and_check_detects(
    tmp_path, monkeypatch, capsys
):
    repo = make_cli_repo(tmp_path, "toyrepo")
    _fake_app_module(monkeypatch)
    (repo / "cli").mkdir()
    (repo / "cli/mytool.usage.extra.kdl").write_text('exit_code 3 "guard refused"\n')
    assert cli.cmd_refresh(repo, SPEC) == 0
    kdl = repo / "cli/mytool.usage.kdl"
    assert kdl.is_file() and "exit_code 3" in kdl.read_text()
    assert cli.cmd_check(repo, SPEC) == 0
    kdl.write_text("# hand edit, contract lies\n")
    assert cli.cmd_check(repo, SPEC) == 1
    assert "stale:   cli/mytool.usage.kdl" in capsys.readouterr().err
    assert cli.cmd_refresh(repo, SPEC) == 0
    assert cli.cmd_check(repo, SPEC) == 0


def test_refresh_skips_an_unimportable_app(tmp_path, capsys):
    # a shim/tool-install context: the consumer app lives in ANOTHER venv -
    # its contract stays the consumer cli:spec task's business, refresh skips.
    repo = make_cli_repo(tmp_path, "toolrepo")
    assert cli.cmd_refresh(repo, SPEC) == 0
    assert "cannot import" in capsys.readouterr().out
    assert not (repo / "cli/mytool.usage.kdl").exists()
    assert cli.cmd_check(repo, SPEC) == 0


def test_render_writes_banner_prefixed_pages_gated_by_check(tmp_path, capsys):
    repo = tmp_path / "repo"
    (repo / "cli").mkdir(parents=True)
    (repo / "cli/toy.usage.kdl").write_text('name toy\nbin toy\nabout "t."\n')
    assert cli.cmd_refresh(repo, SPEC) == 0
    page = repo / "docs/references/cli/toy.md"
    text = page.read_text()
    assert text.startswith(
        "<!-- generated by docs-kit from cli/toy.usage.kdl - do not edit;"
        " mise run docs:refresh -->\n"
    )
    assert "@generated by usage-cli" in text and "fake page" in text
    assert cli.cmd_check(repo, SPEC) == 0
    page.write_text(text + "hand tweak\n")
    assert cli.cmd_check(repo, SPEC) == 1
    assert "stale:   docs/references/cli/toy.md" in capsys.readouterr().err
    page.unlink()
    assert cli.cmd_check(repo, SPEC) == 1
    assert "missing: docs/references/cli/toy.md" in capsys.readouterr().err
    assert cli.cmd_refresh(repo, SPEC) == 0
    assert cli.cmd_check(repo, SPEC) == 0


def test_render_without_usage_binary_is_actionable(tmp_path, monkeypatch):
    repo = tmp_path / "repo"
    (repo / "cli").mkdir(parents=True)
    (repo / "cli/toy.usage.kdl").write_text("name toy\nbin toy\n")
    monkeypatch.setenv("PATH", str(tmp_path / "emptybin"))
    with pytest.raises(SystemExit) as exc:
        cli.cmd_refresh(repo, SPEC)
    assert "'usage' is not on PATH" in str(exc.value)
    assert "mise" in str(exc.value)


def test_lint_failure_breaks_refresh_and_check(tmp_path, capsys):
    repo = tmp_path / "repo"
    (repo / "cli").mkdir(parents=True)
    (repo / "cli/bad.usage.kdl").write_text("name bad\nbin bad\nLINTFAIL\n")
    assert cli.cmd_refresh(repo, SPEC) == 1
    capsys.readouterr()
    assert cli.cmd_check(repo, SPEC) == 1
    assert "lint:    cli/bad.usage.kdl" in capsys.readouterr().err


def test_cli_standard_recipe_teaches_dependency_mode(tmp_path):
    repo = make_cli_repo(tmp_path, "toolrepo")
    assert cli.cmd_init(repo, SPEC, False, "/abs/kit") == 0
    page = (repo / layout.CLI_STANDARD_PAGE).read_text()
    assert "uv run docs-kit spec" in page
    assert "$DOCS_KIT/shared/mise/usage-spec.py" not in page


# --- committed mise glue ------------------------------------------------------


def test_glue_block_canonical_idempotent_and_drift_gated(tmp_path, capsys):
    repo = make_cli_repo(tmp_path, "toolrepo")
    assert cli.cmd_init(repo, SPEC, False, use_mise=True, committed_mise=True) == 0
    text = (repo / "mise.toml").read_text()
    assert text == glue.glue_block(True, False) + "\n"
    cfg = tomllib.loads(text)
    assert cfg["tools"]["usage"] == "latest"
    assert cfg["tasks"]["cli:spec"]["run"] == "uv run docs-kit spec"
    assert "docs-kit check && git diff" in cfg["tasks"]["docs:check"]["run"]
    ign = (repo / ".gitignore").read_text().split()
    assert "mise.local.toml" in ign and ".docs-kit/" not in ign
    assert not (repo / ".docs-kit").exists()
    assert not (repo / "mise.local.toml").exists()
    before = (repo / "mise.toml").read_bytes()
    assert cli.cmd_init(repo, SPEC, False, use_mise=True, committed_mise=True) == 0
    assert (repo / "mise.toml").read_bytes() == before  # idempotent
    assert cli.cmd_check(repo, SPEC) == 0
    # hand-tweak inside the block = drift, remediation names the command
    (repo / "mise.toml").write_text(
        text.replace('run = "uv run docs-kit spec"', 'run = "echo nope"')
    )
    assert cli.cmd_check(repo, SPEC) == 1
    err = capsys.readouterr().err
    assert "docs-kit task block" in err and "--committed" in err
    assert cli.cmd_init(repo, SPEC, False, use_mise=True, committed_mise=True) == 0
    assert (repo / "mise.toml").read_text() == text  # repaired


def test_glue_merges_an_existing_tools_table(tmp_path, capsys):
    repo = make_cli_repo(tmp_path, "toolrepo")
    (repo / "mise.toml").write_text(
        '[tools]\npython = "latest"\n\n[tasks.mine]\nrun = "true"\n'
    )
    assert cli.cmd_init(repo, SPEC, False, use_mise=True, committed_mise=True) == 0
    text = (repo / "mise.toml").read_text()
    assert text.count("[tools]") == 1  # a duplicate header would kill the file
    assert text.startswith('[tools]\nusage = "latest"\npython = "latest"')
    cfg = tomllib.loads(text)
    assert cfg["tasks"]["mine"]["run"] == "true"
    assert cli.cmd_check(repo, SPEC) == 0
    # deleting the usage key from the consumer table is drift again
    (repo / "mise.toml").write_text(text.replace('usage = "latest"\n', "", 1))
    assert cli.cmd_check(repo, SPEC) == 1
    assert "usage key" in capsys.readouterr().err


def test_glue_kit_version_bump_is_drift(tmp_path, monkeypatch):
    repo = make_cli_repo(tmp_path, "toolrepo")
    assert cli.cmd_init(repo, SPEC, False, use_mise=True, committed_mise=True) == 0
    assert cli.cmd_check(repo, SPEC) == 0
    monkeypatch.setattr(glue, "__version__", "9.9.9")
    assert cli.cmd_check(repo, SPEC) == 1
    assert cli.cmd_init(repo, SPEC, False, use_mise=True, committed_mise=True) == 0
    assert "v9.9.9" in (repo / "mise.toml").read_text()
    assert cli.cmd_check(repo, SPEC) == 0


def test_glue_absent_means_shim_mode_not_stale(tmp_path):
    # the exact prior behavior, now explicitly a contract: shim consumers (no
    # committed block) are never told to run --committed by check
    repo = make_repo(tmp_path, "shimmmy", "golang.openapi.json")
    (repo / "mise.local.toml").write_text(shim.mise_block(".docs-kit", cli=True))
    assert cli.cmd_refresh(repo, SPEC) == 0
    assert cli.cmd_check(repo, SPEC) == 0


def test_glue_api_only_variant_has_no_cli_tasks(tmp_path):
    repo = make_repo(tmp_path, "api", "python.openapi.json")
    assert cli.cmd_init(repo, SPEC, False, use_mise=True, committed_mise=True) == 0
    text = (repo / "mise.toml").read_text()
    assert text == glue.glue_block(False, False) + "\n"
    assert "cli:spec" not in text and "[tools]" not in text


def test_committed_requires_with_mise(tmp_path):
    with pytest.raises(SystemExit) as exc:
        cli.main(["init", str(tmp_path), "--committed"])  # click usage error
    assert exc.value.code == 2
