"""docs-kit command line: init / refresh / check (pure file I/O)."""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

from . import __version__, render
from .generator import generate_endpoints_page

REGEN_CMD = "mise run docs:refresh"

VENDORED_SPEC = "docs/reference/openapi.json"
SWAGGER_PAGE = "docs/reference/swagger.html"
API_PAGE = "docs/references/api.md"
ENDPOINTS_PAGE = "docs/references/endpoints.md"

ZENSONFIG = "zensical.toml"
WORKFLOW = ".github/workflows/docs.yml"
GITIGNORE_ENTRIES = ("site/", ".cache/")

# Used only when this run is a legacy `uvx --from <local path>` bootstrap (the
# wheel lives under the uv cache but the source tree is a local checkout).
BAKED_KIT_HOME = "/Users/ladelaru/Dev/me/docs-kit"
KIT_HOME_PLACEHOLDER = "PASTE-PATH-TO-DOCS-KIT-CHECKOUT-OR-REMOVE-THIS"


def _default_kit_home() -> str:
    here = Path(__file__).resolve()
    for parent in here.parents:
        if (parent / ".git").exists() and (parent / "pyproject.toml").is_file():
            return str(parent)
    if os.environ.get("DOCS_KIT"):
        return os.environ["DOCS_KIT"]
    if ".cache" in str(here) and "/uv/" in str(here):
        return BAKED_KIT_HOME
    return KIT_HOME_PLACEHOLDER


def _read_spec(root: Path, spec_name: str) -> tuple[str, dict]:
    path = root / spec_name
    if not path.is_file():
        sys.exit(
            f"ERROR: {spec_name} not found in {root}. "
            "Generate it first (e.g. `mise run openapi`)."
        )
    text = path.read_text(encoding="utf-8")
    try:
        spec = json.loads(text)
    except json.JSONDecodeError as exc:
        sys.exit(f"ERROR: {path} is not valid JSON: {exc}")
    return text, spec


def _generated_outputs(root: Path, spec_name: str) -> list[tuple[Path, str]]:
    text, spec = _read_spec(root, spec_name)
    info = spec.get("info", {})
    title = info.get("title") or root.resolve().name
    return [
        (root / VENDORED_SPEC, text),
        (root / SWAGGER_PAGE, render.render_swagger_page(title)),
        (root / API_PAGE, render.render_api_page()),
        (root / ENDPOINTS_PAGE, generate_endpoints_page(spec, "reference/openapi.json", REGEN_CMD)),
    ]


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def cmd_refresh(root: Path, spec_name: str) -> int:
    for path, content in _generated_outputs(root, spec_name):
        _write(path, content)
        print(f"  wrote {path.relative_to(root)}")
    return 0


def cmd_check(root: Path, spec_name: str) -> int:
    stale: list[str] = []
    for path, content in _generated_outputs(root, spec_name):
        rel = str(path.relative_to(root))
        if not path.exists():
            stale.append(f"missing: {rel}")
        elif path.read_text(encoding="utf-8") != content:
            stale.append(f"stale:   {rel}")
    if stale:
        print("docs are NOT up to date:", file=sys.stderr)
        for line in stale:
            print(f"  {line}", file=sys.stderr)
        print(f"run `{REGEN_CMD}` and commit the result.", file=sys.stderr)
        return 1
    print("docs are up to date")
    return 0


def _scaffold_files(root: Path, spec_name: str) -> list[tuple[Path, str]]:
    _, spec = _read_spec(root, spec_name)
    info = spec.get("info", {})
    title = info.get("title") or root.resolve().name
    description = info.get("description") or ""
    return [
        (root / "docs" / "index.md", render.render_index_page(title, description)),
        (root / "docs" / "tutorials" / "index.md", render.render_section_stub("Tutorials")),
        (root / "docs" / "guides" / "index.md", render.render_section_stub("Guides")),
        (root / "docs" / "explanation" / "index.md", render.render_section_stub("Explanation")),
        (root / "docs" / "references" / "index.md", render.render_section_stub("References")),
        (root / ZENSONFIG, render.render_zensical_toml(title, description)),
        (root / WORKFLOW, render.render_workflow_yml()),
    ]


def _insert_under_table(text: str, header_re: str, line: str) -> tuple[str, bool]:
    """Insert `line` right below the first line matching header_re."""
    m = re.search(rf"(?m)^{header_re}$", text)
    if not m:
        return text, False
    idx = m.end() + 1
    if text[idx : idx + len(line)] == line:
        return text, True
    return text[:idx] + line + "\n" + text[idx:], True


OLD_BLOCK_MARKER = "### docs (block generated by docs-kit init"
INCLUDE_TABLE_RE = r"\[task_config\]"
INCLUDE_LINE = 'includes = ["{{ vars.docs_kit }}/shared/mise/docs.toml"]'
DOCS_SNIPPET = "{{ vars.docs_kit }}/shared/mise/docs.toml"
PULL_TASKS_MARKER = "docs:pull-tasks"
_LOCAL_HEAD = "# docs-kit integration (generated by `docs-kit init --docs-kit {shim}`; put your own overrides ABOVE this block)"
_DOCS_KIT_ENV_LINE = 'DOCS_KIT = "{{ vars.docs_kit }}"'
_PULL_TASKS_RUN = r"""
set -eu
if [ -f {shim}/shared/mise/kit-sync ]; then
  exec sh {shim}/shared/mise/kit-sync {shim}
fi
ver="$({ docs-kit --version 2>/dev/null || uv run --no-dev docs-kit --version; } 2>/dev/null | awk '{print $2}')"
if [ -z "$ver" ]; then
  echo "pull-tasks: no docs-kit on PATH or uv project here; install the CLI first (kit README section 1)" >&2
  exit 1
fi
v="v$ver"
if [ ! -d {shim} ]; then
  git clone -q -c advice.detachedHead=false --depth 1 --branch "$v" \
    --filter=blob:none --sparse git@github.com:ldelarue/docs-kit.git {shim}
  git -C {shim} -c advice.detachedHead=false sparse-checkout set --no-cone '/shared/mise/'
fi
if [ "$(git -C {shim} describe --tags --exact-match 2>/dev/null || true)" != "$v" ]; then
  git -C {shim} fetch -q --depth 1 origin "+refs/tags/$v:refs/tags/$v"
  git -C {shim} -c advice.detachedHead=false checkout -q "$v"
fi
git -C {shim} -c advice.detachedHead=false sparse-checkout set --no-cone '/shared/mise/' 2>/dev/null || true
echo "docs task layer pinned at $v (frozen fallback; kit-sync engine file arrives with a later release)"
"""


def _is_kit_shim(kit_home: str) -> bool:
    """True when the recorded docs_kit path is a repo-local download shim."""
    return bool(kit_home) and kit_home != KIT_HOME_PLACEHOLDER and not Path(kit_home).is_absolute()


def _pull_tasks_block(shim: str) -> str:
    return (
        f'[tasks."{PULL_TASKS_MARKER}"]\n'
        'description = "Fetch docs-kit task files (shared/mise) at the installed CLI\'s tag"\n'
        + "run = '''\n"
        + _PULL_TASKS_RUN.replace("{shim}", shim).lstrip("\n")
        + "'''\n"
    )


def _local_shim_block(shim: str) -> str:
    return (
        _LOCAL_HEAD.replace("{shim}", shim)
        + "\n[vars]\n"
        + f'docs_kit = "{shim}"\n\n[env]\n'
        + _DOCS_KIT_ENV_LINE
        + "\n\n[task_config]\n"
        + f'includes = ["{DOCS_SNIPPET}"]\n\n'
        + _pull_tasks_block(shim)
    )

_BLOCK_ANNOTATION = """
### docs integration (generated by docs-kit init; see docs-kit README) ###
# The docs:* task BODIES live in the docs-kit clone at
#   <docs-kit>/shared/mise/docs.toml
# included below - single source: updating that file (a `git pull` in the
# clone) updates every consumer repo instantly. Never duplicate them here.
# Docs tasks suddenly missing? Re-run `docs-kit init` - it repairs this block.
# Per-machine clone path: override in mise.local.toml (add it to .gitignore):
#   [vars]
#   docs_kit = "/your/path/to/docs-kit"
"""


def _ensure_key(
    text: str,
    table_label: str,
    table_re: str,
    key: str,
    line: str,
    to_append: list[tuple[str, str]],
) -> str:
    """Guarantee the assignment `line` for `key` inside its table."""
    if line in text:
        print(f"  .mise.toml: `{key}` already set, kept")
        return text
    m = re.search(rf"(?m)^\s*{re.escape(key)}\s*=.*$", text)
    if m:
        text = text[: m.start()] + line + text[m.end() :]
        print(f"  .mise.toml: rewrote `{key}` (value changed)")
        return text
    if re.search(rf"(?m)^{table_re}$", text):
        text, _ = _insert_under_table(text, table_re, line)
        print(f"  .mise.toml: added `{key}`")
    else:
        to_append.append((table_label, line))
    return text


def _ensure_include(
    text: str, snippet: str, to_append: list[tuple[str, str]]
) -> str:
    """Guarantee `snippet` is one entry of the (single-line) includes array."""
    if snippet in text:
        print(f"  .mise.toml: include `{snippet.rsplit('/', 1)[-1]}` already set, kept")
        return text
    m = re.search(r"(?m)^includes = \[.*\]$", text)
    if m:
        text = text[: m.start()] + m.group(0)[:-1] + f', "{snippet}"]' + text[m.end() :]
        print(f"  .mise.toml: added `{snippet.rsplit('/', 1)[-1]}` to existing includes")
        return text
    for i, (table, line) in enumerate(to_append):
        if table == "task_config" and line.startswith("includes = ["):
            to_append[i] = (table, line[:-1] + f', "{snippet}"]')
            return text
    to_append.append(("task_config", f'includes = ["{snippet}"]'))
    return text


_LOCAL_HEAD_MARK = "# docs-kit integration (generated"


def _strip_shim_lines(text: str, shim: str) -> str:
    """Drop previously generated shim lines; they live in mise.local.toml now."""
    removed = False

    def drop(t: str, pattern: str, label: str, eol: bool = True) -> str:
        nonlocal removed
        new_t, n = re.subn(rf"(?m){pattern}" + (r"\n" if eol else ""), "", t)
        if n:
            removed = True
            print(f"  .mise.toml: removed generated `{label}` (now in mise.local.toml)")
        return new_t

    text = drop(text, re.escape(f'docs_kit = "{shim}"'), "docs_kit")
    text = drop(text, re.escape(_DOCS_KIT_ENV_LINE), "DOCS_KIT")
    text = drop(text, re.escape(INCLUDE_LINE), "docs include")
    for alt in (
        '", "' + re.escape(DOCS_SNIPPET) + '"',
        '"' + re.escape(DOCS_SNIPPET) + '", "',
    ):
        text = drop(text, alt, "docs include entry")
    text = drop(
        text,
        r'\[tasks\."docs:(?:kit-sync|pull-tasks)"\][^\n]*\n(?:.*\n)*?(?=^\[|\Z)',
        "generated sync/pull task",
        eol=False,
    )
    text = drop(text, r'"docs:(?:kit-sync|pull-tasks)" = \{.*\}\n?', "generated sync/pull task", eol=False)
    if removed:
        lines = text.splitlines(keepends=True)
        keep, i, headers = [], 0, {"[vars]", "[env]", "[task_config]"}
        while i < len(lines):
            stripped = lines[i].strip()
            if stripped in headers:
                j = i + 1
                while j < len(lines) and not lines[j].strip().startswith("["):
                    body = lines[j].strip()
                    if body and not body.startswith("#"):
                        break
                    j += 1
                if j >= len(lines) or lines[j].strip().startswith("["):
                    i += 1  # section empty -> drop the header line
                    continue
            keep.append(lines[i])
            i += 1
        text = "".join(keep)
    return text


def _integrate_local_shim(root: Path, shim: str) -> None:
    path = root / "mise.local.toml"
    block = _local_shim_block(shim)
    text = path.read_text(encoding="utf-8") if path.exists() else ""
    i = text.find(_LOCAL_HEAD_MARK)
    if i != -1:
        if PULL_TASKS_MARKER in text[i:]:
            print("  mise.local.toml: replaced previously generated block")
        text = text[:i]
    text = text.rstrip("\n")
    if text:
        text += "\n\n"
    _write(path, text + block)
    print("  mise.local.toml: generated docs-kit integration (kept out of git)")


def _integrate_mise(root: Path, kit_home: str) -> None:
    path = root / ".mise.toml"
    text = path.read_text(encoding="utf-8") if path.exists() else ""
    migrated = False

    # Migrate the old duplicated-tasks block to the shared form when possible.
    if INCLUDE_LINE not in text and OLD_BLOCK_MARKER in text:
        idx = text.index(OLD_BLOCK_MARKER)
        old_tail = text[idx:]
        foreign = [
            line
            for line in old_tail.splitlines()
            if re.match(r'\[tasks\.', line) and "docs:" not in line
        ]
        if foreign:
            print(
                "  ERROR: old docs block found, but foreign tasks follow it in\n"
                "  .mise.toml; move your own [tasks.*] entries ABOVE the\n"
                "  '### docs' marker, then re-run docs-kit init to migrate."
            )
            return
        text = text[:idx].rstrip("\n") + "\n"
        migrated = True

    # uv must exist (tasks use uvx fallbacks; the pypi backend installs via uv).
    if not re.search(r'(?m)^\s*uv\s=', text):
        header = r'\[tools\]'
        if re.search(rf"(?m)^{header}$", text):
            text, _ = _insert_under_table(text, header, 'uv = "latest"')
        else:
            text = '[tools]\nuv = "latest"\n\n' + text

    needed = (
        f'docs_kit = "{kit_home}"',
        _DOCS_KIT_ENV_LINE,
        DOCS_SNIPPET,
    )
    if _is_kit_shim(kit_home):
        text = _strip_shim_lines(text, kit_home)
        _write(path, text)
        _integrate_local_shim(root, kit_home)
        return
    if DOCS_SNIPPET in text and OLD_BLOCK_MARKER not in text and all(line in text for line in needed):
        print("  .mise.toml: docs integration present, left untouched")
        return

    to_append: list[tuple[str, str]] = []
    text = _ensure_key(text, "vars", r"\[vars\]", "docs_kit", f'docs_kit = "{kit_home}"', to_append)
    text = _ensure_key(
        text, "env", r"\[env\]", "DOCS_KIT", 'DOCS_KIT = "{{ vars.docs_kit }}"', to_append
    )
    text = _ensure_include(text, DOCS_SNIPPET, to_append)

    if to_append:
        tables: dict[str, list[str]] = {}
        for table, line in to_append:
            tables.setdefault(table, []).append(line)
        block = _BLOCK_ANNOTATION + "".join(
            f"\n[{t}]\n" + "\n".join(lines) + "\n" for t, lines in tables.items()
        )
        text = text.rstrip("\n") + "\n" + block
    _write(path, text)
    print("  updated .mise.toml (" + ("migrated to shared tasks" if migrated else "docs integration") + ")")
    if kit_home == KIT_HOME_PLACEHOLDER:
        print(
            f"  WARNING: vars.docs_kit is '{KIT_HOME_PLACEHOLDER}' because this\n"
            "  init run could not detect a docs-kit checkout. Replace the value\n"
            "  with the absolute path of your clone (or override it via\n"
            "  mise.local.toml). See docs-kit README."
        )


def _integrate_gitignore(root: Path, extra: tuple[str, ...] = ()) -> None:
    path = root / ".gitignore"
    text = path.read_text(encoding="utf-8") if path.exists() else ""
    lines = text.splitlines()
    entries = GITIGNORE_ENTRIES + tuple(e for e in extra if e and e not in GITIGNORE_ENTRIES)
    added = [e for e in entries if e not in lines]
    if not added:
        print("  .gitignore: already covers", ", ".join(entries))
        return
    text = text.rstrip("\n")
    if text:
        text += "\n"
    text += "\n".join(added) + "\n"
    _write(path, text)
    print(f"  .gitignore: added {', '.join(added)}")


def cmd_init(root: Path, spec_name: str, force: bool, kit_home: str) -> int:
    """Install or repair the docs integration (idempotent).

    - missing files            -> written
    - byte-identical files     -> skipped
    - existing files that differ (hand edits) -> only overwritten with --force
    - missing mise/gitignore parts -> re-added (repairs a deleted block)
    """
    scaffold = [(p, c, "scaffold") for p, c in _scaffold_files(root, spec_name)]
    generated = [(p, c, "generated") for p, c in _generated_outputs(root, spec_name)]
    plan: list[tuple[Path, str]] = []
    conflicts: list[str] = []
    gen_conflicts: list[str] = []
    unchanged: list[str] = []
    for path, content, kind in scaffold + generated:
        if not path.exists():
            plan.append((path, content))
            continue
        if path.read_text(encoding="utf-8") == content:
            unchanged.append(str(path.relative_to(root)))
        elif force:
            plan.append((path, content))
        elif kind == "generated":
            gen_conflicts.append(str(path.relative_to(root)))
        else:
            conflicts.append(str(path.relative_to(root)))
    if conflicts or gen_conflicts:
        parts = ["ERROR: existing files differ from what docs-kit would generate (not touched):"]
        for rel in gen_conflicts:
            parts.append(f"  generated: {rel}   -> fix with `mise run docs:refresh` instead")
        for rel in conflicts:
            parts.append(f"  hand-written: {rel}")
        parts.append("Review them, or re-run with --force to overwrite.")
        sys.exit("\n".join(parts))
    for path, content in plan:
        _write(path, content)
        print(f"  wrote {path.relative_to(root)}")
    for rel in unchanged:
        print(f"  unchanged {rel}")
    if not plan:
        print("  scaffold already complete (nothing to write)")
    _integrate_gitignore(
        root,
        ()
        if not _is_kit_shim(kit_home)
        else (kit_home.rstrip("/") + "/", "mise.local.toml"),
    )
    _integrate_mise(root, kit_home)
    print("done. Next: `mise run docs:refresh` to verify, then commit.")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="docs-kit", description=__doc__)
    parser.add_argument("--version", action="version", version=f"%(prog)s {__version__}")
    sub = parser.add_subparsers(dest="command", required=True)

    def common(p: argparse.ArgumentParser) -> None:
        p.add_argument("root", nargs="?", default=".", help="target repo (default: cwd)")
        p.add_argument("--spec", default="openapi.json", help="spec file relative to root")

    p_init = sub.add_parser("init", help="scaffold a Zensical docs site in a repo")
    common(p_init)
    p_init.add_argument("--force", action="store_true", help="overwrite scaffold files")
    p_init.add_argument("--docs-kit", default=_default_kit_home(), help="path recorded as $DOCS_KIT")
    p_refresh = sub.add_parser("refresh", help="regenerate all generated docs files")
    common(p_refresh)
    p_check = sub.add_parser("check", help="fail if generated docs files are stale")
    common(p_check)

    args = parser.parse_args(argv)
    root = Path(args.root).resolve()
    if args.command == "init":
        return cmd_init(root, args.spec, args.force, args.docs_kit)
    if args.command == "refresh":
        return cmd_refresh(root, args.spec)
    return cmd_check(root, args.spec)


if __name__ == "__main__":
    sys.exit(main())
