"""docs-kit command line: init / refresh / check (pure file I/O)."""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

from . import __version__, render
from .generator import generate_endpoints_page

REGEN_CMD = "mise run docs:refresh"

VENDORED_SPEC = "docs/reference/openapi.json"
SWAGGER_PAGE = "docs/reference/swagger.html"
API_PAGE = "docs/references/api.md"
ENDPOINTS_PAGE = "docs/references/endpoints.md"

ZENSONFIG = "zensical.toml"
WORKFLOW = ".github/workflows/docs.yml"
GITIGNORE_ENTRIES = ("site/", ".cache/")

# Used only when this run is a legacy `uvx --from <local path>` bootstrap (the
# wheel lives under the uv cache but the source tree is a local checkout).
BAKED_KIT_HOME = "/Users/ladelaru/Dev/me/docs-kit"
KIT_HOME_PLACEHOLDER = "PASTE-PATH-TO-DOCS-KIT-CHECKOUT-OR-REMOVE-THIS"


def _default_kit_home() -> str:
    here = Path(__file__).resolve()
    for parent in here.parents:
        if (parent / ".git").exists() and (parent / "pyproject.toml").is_file():
            return str(parent)
    if os.environ.get("DOCS_KIT"):
        return os.environ["DOCS_KIT"]
    if ".cache" in str(here) and "/uv/" in str(here):
        return BAKED_KIT_HOME
    return KIT_HOME_PLACEHOLDER


def _read_spec(root: Path, spec_name: str) -> tuple[str, dict]:
    path = root / spec_name
    if not path.is_file():
        sys.exit(
            f"ERROR: {spec_name} not found in {root}. "
            "Generate it first (e.g. `mise run openapi`)."
        )
    text = path.read_text(encoding="utf-8")
    try:
        spec = json.loads(text)
    except json.JSONDecodeError as exc:
        sys.exit(f"ERROR: {path} is not valid JSON: {exc}")
    return text, spec


def _generated_outputs(root: Path, spec_name: str) -> list[tuple[Path, str]]:
    text, spec = _read_spec(root, spec_name)
    info = spec.get("info", {})
    title = info.get("title") or root.resolve().name
    return [
        (root / VENDORED_SPEC, text),
        (root / SWAGGER_PAGE, render.render_swagger_page(title)),
        (root / API_PAGE, render.render_api_page()),
        (root / ENDPOINTS_PAGE, generate_endpoints_page(spec, "reference/openapi.json", REGEN_CMD)),
    ]


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def cmd_refresh(root: Path, spec_name: str) -> int:
    for path, content in _generated_outputs(root, spec_name):
        _write(path, content)
        print(f"  wrote {path.relative_to(root)}")
    return 0


def cmd_check(root: Path, spec_name: str) -> int:
    stale: list[str] = []
    for path, content in _generated_outputs(root, spec_name):
        rel = str(path.relative_to(root))
        if not path.exists():
            stale.append(f"missing: {rel}")
        elif path.read_text(encoding="utf-8") != content:
            stale.append(f"stale:   {rel}")
    if stale:
        print("docs are NOT up to date:", file=sys.stderr)
        for line in stale:
            print(f"  {line}", file=sys.stderr)
        print(f"run `{REGEN_CMD}` and commit the result.", file=sys.stderr)
        return 1
    print("docs are up to date")
    return 0


def _scaffold_files(root: Path, spec_name: str) -> list[tuple[Path, str]]:
    _, spec = _read_spec(root, spec_name)
    info = spec.get("info", {})
    title = info.get("title") or root.resolve().name
    description = info.get("description") or ""
    return [
        (root / "docs" / "index.md", render.render_index_page(title, description)),
        (root / "docs" / "tutorials" / "index.md", render.render_section_stub("Tutorials")),
        (root / "docs" / "guides" / "index.md", render.render_section_stub("Guides")),
        (root / "docs" / "explanation" / "index.md", render.render_section_stub("Explanation")),
        (root / "docs" / "references" / "index.md", render.render_section_stub("References")),
        (root / ZENSONFIG, render.render_zensical_toml(title, description)),
        (root / WORKFLOW, render.render_workflow_yml()),
    ]


def _insert_under_table(text: str, header_re: str, line: str) -> tuple[str, bool]:
    """Insert `line` right below the first line matching header_re."""
    m = re.search(rf"(?m)^{header_re}$", text)
    if not m:
        return text, False
    idx = m.end() + 1
    if text[idx : idx + len(line)] == line:
        return text, True
    return text[:idx] + line + "\n" + text[idx:], True


OLD_BLOCK_MARKER = "### docs (block generated by docs-kit init"
INCLUDE_TABLE_RE = r"\[task_config\]"
INCLUDE_LINE = 'includes = ["{{ vars.docs_kit }}/shared/mise/docs.toml"]'

_BLOCK_ANNOTATION = """
### docs integration (generated by docs-kit init; see docs-kit README) ###
# The docs:* task BODIES live in the docs-kit clone at
#   <docs-kit>/shared/mise/docs.toml
# included below - single source: updating that file (a `git pull` in the
# clone) updates every consumer repo instantly. Never duplicate them here.
# Docs tasks suddenly missing? Re-run `docs-kit init` - it repairs this block.
# Per-machine clone path: override in mise.local.toml (add it to .gitignore):
#   [vars]
#   docs_kit = "/your/path/to/docs-kit"
"""


def _integrate_mise(root: Path, kit_home: str, spec_name: str) -> None:
    path = root / ".mise.toml"
    text = path.read_text(encoding="utf-8") if path.exists() else ""
    migrated = False

    # Migrate the old duplicated-tasks block to the shared form when possible.
    if INCLUDE_LINE not in text and OLD_BLOCK_MARKER in text:
        idx = text.index(OLD_BLOCK_MARKER)
        old_tail = text[idx:]
        foreign = [
            line
            for line in old_tail.splitlines()
            if re.match(r'\[tasks\.', line) and "docs:" not in line
        ]
        if foreign:
            print(
                "  ERROR: old docs block found, but foreign tasks follow it in\n"
                "  .mise.toml; move your own [tasks.*] entries ABOVE the\n"
                "  '### docs' marker, then re-run docs-kit init to migrate."
            )
            return
        text = text[:idx].rstrip("\n") + "\n"
        migrated = True

    if INCLUDE_LINE in text and OLD_BLOCK_MARKER not in text:
        needed = (
            f'docs_kit = "{kit_home}"',
            'DOCS_KIT = "{{ vars.docs_kit }}"',
            INCLUDE_LINE,
        )
        if all(line in text for line in needed):
            print("  .mise.toml: shared-tasks integration present, left untouched")
            return

    # uv must exist (tasks use uvx fallbacks; the pypi backend installs via uv).
    if not re.search(r'(?m)^\s*uv\s=', text):
        header = r'\[tools\]'
        if re.search(rf"(?m)^{header}$", text):
            text, _ = _insert_under_table(text, header, 'uv = "latest"')
        else:
            text = '[tools]\nuv = "latest"\n\n' + text

    steps = [
        ("vars", r"\[vars\]", 'docs_kit = "{kit}"', {"kit": kit_home}),
        ("env", r"\[env\]", 'DOCS_KIT = "{{ vars.docs_kit }}"', {}),
        ("task_config", INCLUDE_TABLE_RE, INCLUDE_LINE, {}),
    ]
    to_append: list[tuple[str, str]] = []
    for table, header_re, line, fmt in steps:
        line = line.format(**fmt) if fmt else line
        m = re.search(rf"(?m)^{header_re}$", text)
        if m and line in text:
            print(f"  .mise.toml: `{line.split(' =')[0]}` already set, kept")
        elif m:
            text, _ = _insert_under_table(text, header_re, line)
        else:
            to_append.append((table, line))

    if to_append:
        tables: dict[str, list[str]] = {}
        for table, line in to_append:
            tables.setdefault(table, []).append(line)
        block = _BLOCK_ANNOTATION + "".join(
            f"\n[{t}]\n" + "\n".join(lines) + "\n" for t, lines in tables.items()
        )
        text = text.rstrip("\n") + "\n" + block
    _write(path, text)
    print("  updated .mise.toml (" + ("migrated to shared tasks" if migrated else "shared-tasks integration") + ")")
    if kit_home == KIT_HOME_PLACEHOLDER:
        print(
            f"  WARNING: vars.docs_kit is '{KIT_HOME_PLACEHOLDER}' because this\n"
            "  init run could not detect a docs-kit checkout. Replace the value\n"
            "  with the absolute path of your clone (or override it via\n"
            "  mise.local.toml). See docs-kit README."
        )


def _integrate_gitignore(root: Path) -> None:
    path = root / ".gitignore"
    text = path.read_text(encoding="utf-8") if path.exists() else ""
    lines = text.splitlines()
    added = [e for e in GITIGNORE_ENTRIES if e not in lines]
    if not added:
        print("  .gitignore: already covers", ", ".join(GITIGNORE_ENTRIES))
        return
    text = text.rstrip("\n")
    if text:
        text += "\n"
    text += "\n".join(added) + "\n"
    _write(path, text)
    print(f"  .gitignore: added {', '.join(added)}")


def cmd_init(root: Path, spec_name: str, force: bool, kit_home: str) -> int:
    """Install or repair the docs integration (idempotent).

    - missing files            -> written
    - byte-identical files     -> skipped
    - existing files that differ (hand edits) -> only overwritten with --force
    - missing mise/gitignore parts -> re-added (repairs a deleted block)
    """
    scaffold = [(p, c, "scaffold") for p, c in _scaffold_files(root, spec_name)]
    generated = [(p, c, "generated") for p, c in _generated_outputs(root, spec_name)]
    plan: list[tuple[Path, str]] = []
    conflicts: list[str] = []
    gen_conflicts: list[str] = []
    unchanged: list[str] = []
    for path, content, kind in scaffold + generated:
        if not path.exists():
            plan.append((path, content))
            continue
        if path.read_text(encoding="utf-8") == content:
            unchanged.append(str(path.relative_to(root)))
        elif force:
            plan.append((path, content))
        elif kind == "generated":
            gen_conflicts.append(str(path.relative_to(root)))
        else:
            conflicts.append(str(path.relative_to(root)))
    if conflicts or gen_conflicts:
        parts = ["ERROR: existing files differ from what docs-kit would generate (not touched):"]
        for rel in gen_conflicts:
            parts.append(f"  generated: {rel}   -> fix with `mise run docs:refresh` instead")
        for rel in conflicts:
            parts.append(f"  hand-written: {rel}")
        parts.append("Review them, or re-run with --force to overwrite.")
        sys.exit("\n".join(parts))
    for path, content in plan:
        _write(path, content)
        print(f"  wrote {path.relative_to(root)}")
    for rel in unchanged:
        print(f"  unchanged {rel}")
    if not plan:
        print("  scaffold already complete (nothing to write)")
    _integrate_gitignore(root)
    _integrate_mise(root, kit_home, spec_name)
    print("done. Next: `mise run docs:refresh` to verify, then commit.")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="docs-kit", description=__doc__)
    parser.add_argument("--version", action="version", version=f"%(prog)s {__version__}")
    sub = parser.add_subparsers(dest="command", required=True)

    def common(p: argparse.ArgumentParser) -> None:
        p.add_argument("root", nargs="?", default=".", help="target repo (default: cwd)")
        p.add_argument("--spec", default="openapi.json", help="spec file relative to root")

    p_init = sub.add_parser("init", help="scaffold a Zensical docs site in a repo")
    common(p_init)
    p_init.add_argument("--force", action="store_true", help="overwrite scaffold files")
    p_init.add_argument("--docs-kit", default=_default_kit_home(), help="path recorded as $DOCS_KIT")
    p_refresh = sub.add_parser("refresh", help="regenerate all generated docs files")
    common(p_refresh)
    p_check = sub.add_parser("check", help="fail if generated docs files are stale")
    common(p_check)

    args = parser.parse_args(argv)
    root = Path(args.root).resolve()
    if args.command == "init":
        return cmd_init(root, args.spec, args.force, args.docs_kit)
    if args.command == "refresh":
        return cmd_refresh(root, args.spec)
    return cmd_check(root, args.spec)


if __name__ == "__main__":
    sys.exit(main())
