"""The generated set: `refresh` writes it, `check` diffs it, `spec` feeds the CLI half."""

from __future__ import annotations

import json
import sys
from pathlib import Path

from . import render, render_cli, usage_spec
from .detect import Bins, Recipe, detect_pipelines, github_detected
from .files import rel, write
from .generator import generate_endpoints_page
from .glue import check_glue
from .layout import (
    API_PAGE,
    API_SPEC_DEFAULT,
    CLI_DIR,
    CLI_STANDARD_PAGE,
    ENDPOINTS_PAGE,
    KDL_EXTRA_SUFFIX,
    KDL_SUFFIX,
    REGEN_CMD,
    SWAGGER_PAGE,
    VENDORED_SPEC,
    WORKFLOW,
)
from .term import Color, added, paint


def read_spec(root: Path, spec_name: str) -> tuple[str, dict]:
    path = root / spec_name
    if not path.is_file():
        sys.exit(
            f"ERROR: {spec_name} not found in {root}. "
            "Export your API spec there first, or point at it with --spec."
        )
    text = path.read_text(encoding="utf-8")
    try:
        spec = json.loads(text)
    except json.JSONDecodeError as exc:
        sys.exit(f"ERROR: {path} is not valid JSON: {exc}")
    return text, spec


def generated_outputs(
    root: Path, spec_name: str, api: bool, github: bool
) -> list[tuple[Path, str]]:
    """The kit-owned files for THIS repository: API pages when an OpenAPI
    spec is present; the CI workflow only on GitHub."""
    out: list[tuple[Path, str]] = []
    if api:
        text, spec = read_spec(root, spec_name)
        title = spec.get("info", {}).get("title") or root.resolve().name
        out += [
            (root / VENDORED_SPEC, text),
            (root / SWAGGER_PAGE, render.render_swagger_page(title)),
            (root / API_PAGE, render.render_api_page()),
            (
                root / ENDPOINTS_PAGE,
                generate_endpoints_page(spec, "reference/openapi.json", REGEN_CMD),
            ),
        ]
    if github:
        out.append((root / WORKFLOW, render.render_workflow_yml()))
    return out


def _extra_text(root: Path, name: str) -> str | None:
    path = root / CLI_DIR / f"{name}{KDL_EXTRA_SUFFIX}"
    return path.read_text(encoding="utf-8") if path.is_file() else None


def _emit_contract(out: Path, text: str, root: Path) -> None:
    """Byte-stable contract write with refresh-style reporting."""
    if out.is_file() and out.read_text(encoding="utf-8") == text:
        print(paint(f"  contract current: {rel(out, root)}", Color.DIM))
        return
    write(out, text)
    added(rel(out, root))


def _respec_committed(root: Path, bins: Bins, *, check_only: bool = False) -> list[str]:
    """Regenerate (or diff-check) the contract of every Typer bin.

    Go bins need their cobra core piped (`cli:spec` owns them); kdl/unknown
    contracts ARE the source. A Typer app that cannot be imported in THIS
    venv (tool/shim installs) is skipped: its own `docs-kit spec` run in the
    consumer's venv writes the same bytes.
    """
    stale: list[str] = []
    for name, info in sorted(bins.items()):
        if info.get("recipe") != Recipe.PYTHON or not info.get("app"):
            continue
        out = root / CLI_DIR / f"{name}{KDL_SUFFIX}"
        try:
            app = usage_spec.load_app(info["app"])
        except ImportError:
            print(
                paint(
                    f"  note: {name}: cannot import {info['app']} here - the"
                    " contract is regenerated by `uv run docs-kit spec` (its own venv)",
                    Color.DIM,
                )
            )
            continue
        text = usage_spec.render_text(
            usage_spec.typer_export(app, name), _extra_text(root, name)
        )
        if not check_only:
            _emit_contract(out, text, root)
        elif not out.is_file():
            stale.append(f"missing: {rel(out, root)}")
        elif out.read_text(encoding="utf-8") != text:
            stale.append(f"stale:   {rel(out, root)}")
    return stale


def cmd_refresh(
    root: Path,
    spec_name: str = API_SPEC_DEFAULT,
    *,
    spec_explicit: bool = False,
    extra_bins: list[str] | None = None,
    no_api: bool = False,
    no_cli: bool = False,
) -> int:
    api, bins = detect_pipelines(
        root, spec_name, spec_explicit, extra_bins or [], no_api=no_api, no_cli=no_cli
    )
    for path, content in generated_outputs(root, spec_name, api, github_detected(root)):
        if path.is_file() and path.read_text(encoding="utf-8") == content:
            continue
        write(path, content)
        added(rel(path, root))
    if bins and not (root / CLI_STANDARD_PAGE).is_file():
        print(
            paint(
                f"  note: CLI{'' if len(bins) == 1 else 's'} detected"
                f" ({', '.join(sorted(bins))}) - run `docs-kit init` to scaffold"
                " the reference pages, `mise run docs:refresh` to render them",
                Color.DIM,
            )
        )
    if bins:
        _respec_committed(root, bins)
    return 0 if no_cli else render_cli.cmd_render(root)


def cmd_check(
    root: Path,
    spec_name: str = API_SPEC_DEFAULT,
    *,
    spec_explicit: bool = False,
    extra_bins: list[str] | None = None,
    no_api: bool = False,
    no_cli: bool = False,
) -> int:
    api, bins = detect_pipelines(
        root, spec_name, spec_explicit, extra_bins or [], no_api=no_api, no_cli=no_cli
    )
    stale: list[str] = []
    for path, content in generated_outputs(root, spec_name, api, github_detected(root)):
        if not path.exists():
            stale.append(f"missing: {rel(path, root)}")
        elif path.read_text(encoding="utf-8") != content:
            stale.append(f"stale:   {rel(path, root)}")
    if bins:
        stale += _respec_committed(root, bins, check_only=True)
    if not no_cli:
        stale += render_cli.check_rendered(root)
    glue_stale, glue_hint = check_glue(root)
    stale += glue_stale
    if not stale:
        print("docs are up to date")
        return 0
    print("docs are NOT up to date:", file=sys.stderr)
    for line in stale:
        print(f"  {line}", file=sys.stderr)
    if glue_hint:
        print(glue_hint, file=sys.stderr)
    print(f"run `{REGEN_CMD}` and commit the result.", file=sys.stderr)
    return 1


def cmd_spec(
    root: Path,
    *,
    bins: list[str] | None = None,
    extra: str | None = None,
    out: str | None = None,
    no_cli: bool = False,
) -> int:
    """Regenerate cli/<bin>.usage.kdl from the code behind it.

    Typer bins are introspected in THIS venv; Go bins read their cobra core
    from stdin (`go run . --usage-spec | docs-kit spec --bin mycli`);
    kdl/unknown bins have no code to regen from. --extra/--out override the
    cli/<bin>.usage.extra.kdl / cli/<bin>.usage.kdl conventions for one contract.
    """
    explicit = list(bins or [])
    _, detected = detect_pipelines(
        root, API_SPEC_DEFAULT, False, explicit, no_api=True, no_cli=no_cli
    )
    targets = {n: detected[n] for n in (explicit or sorted(detected))}
    if not targets:
        print(
            paint(
                "no CLI evidence (cli/, typer console script, go.mod+cobra)", Color.DIM
            )
        )
        return 0
    if (extra or out) and len(targets) != 1:
        sys.exit("ERROR: --extra/--out address one contract - name it with --bin NAME")
    for name, info in sorted(targets.items()):
        recipe = info.get("recipe")
        if extra:
            extra_path = root / extra  # an absolute extra wins the join
            if not extra_path.is_file():
                sys.exit(
                    f"ERROR: extra spec {extra} not found; create it or drop --extra"
                )
            extra_text = extra_path.read_text(encoding="utf-8")
        else:
            extra_text = _extra_text(root, name)
        target = root / out if out else root / CLI_DIR / f"{name}{KDL_SUFFIX}"
        if recipe == Recipe.PYTHON:
            app = usage_spec.load_app(info["app"])
            core = usage_spec.typer_export(app, name)
        elif recipe == Recipe.GO or (
            explicit and recipe == Recipe.UNKNOWN and not sys.stdin.isatty()
        ):
            if sys.stdin.isatty():
                sys.exit(
                    f"ERROR: {name}'s core is cobra's - pipe it: "
                    f"`go run . --usage-spec | docs-kit spec --bin {name}`"
                )
            core = sys.stdin.read()
        else:
            print(
                paint(
                    f"  {name}: hand-written contract (no code to regen)"
                    f" - leave {rel(target, root)} authored",
                    Color.DIM,
                )
            )
            continue
        _emit_contract(target, usage_spec.render_text(core, extra_text), root)
    return 0
