"""CLI reference pages: `usage` over cli/*.usage.kdl -> docs/references/cli/.

Port of `shared/mise/render-cli-docs`, which stays untouched for shim/no-venv
consumers. Same contract, in-process: for every committed contract, `usage
lint` first (a broken contract fails the pipeline, standard §3), then
`usage generate markdown --out-file -`, docs-kit banner prepended, written to
`docs/references/cli/<bin>.md`. Output is byte-stable (no timestamps), so
`docs:check` can diff it or compare it without writing. Never hand-edit pages.

`usage` is an external binary resolved on PATH: the committed glue block and
the shim init block both pin `[tools] usage = "latest"` so mise/CI provide it.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

CLI_DIR = "cli"
KDL_SUFFIX = ".usage.kdl"
KDL_EXTRA_SUFFIX = ".usage.extra.kdl"
CLI_PAGE_DIR = "docs/references/cli"

# must stay byte-identical to the banner `shared/mise/render-cli-docs` writes
# (committed pages predate the port; the byte-stability contract crosses it)
PAGE_BANNER = (
    "<!-- generated by docs-kit from {kdl} - do not edit; mise run docs:refresh -->"
)

USAGE_MISSING_HINT = (
    "ERROR: 'usage' is not on PATH.\n"
    "  dependency mode: the committed docs-kit glue block pins\n"
    '  [tools] usage = "latest" in mise.toml - run `mise install` (or `docs-kit\n'
    "  init --with-mise --committed` to add it);\n"
    "  shim mode: the init block in mise.local.toml pins it the same way;\n"
    "  one-off: mise use -g usage@latest"
)


def usage_binary() -> str:
    usage = shutil.which("usage")
    if not usage:
        sys.exit(USAGE_MISSING_HINT)
    return usage


def contract_kdls(root: Path) -> dict[str, str]:
    """bin -> contract path relative to root, for committed cli/*.usage.kdl
    (hand-written extras are never a rendering source)."""
    out: dict[str, str] = {}
    cli_dir = root / CLI_DIR
    if cli_dir.is_dir():
        for path in sorted(cli_dir.glob(f"*{KDL_SUFFIX}")):
            if path.name.endswith(KDL_EXTRA_SUFFIX):
                continue
            out[path.name[: -len(KDL_SUFFIX)]] = path.relative_to(root).as_posix()
    return out


def _lint(usage: str, root: Path, kdl_rel: str) -> bool:
    return (
        subprocess.run([usage, "lint", kdl_rel], cwd=root, check=False).returncode == 0
    )


def render_page(usage: str, root: Path, kdl_rel: str) -> str | None:
    """The full page bytes for one contract, or None when lint rejects it."""
    if not _lint(usage, root, kdl_rel):
        print(
            f"docs-kit: usage lint failed on {kdl_rel} - regenerate with "
            "`docs-kit spec` / `mise run cli:spec` (never hand-edit the "
            "contract)",
            file=sys.stderr,
        )
        return None
    proc = subprocess.run(
        [usage, "generate", "markdown", "-f", kdl_rel, "--out-file", "-"],
        cwd=root,
        capture_output=True,
        text=True,
        check=False,
    )
    if proc.returncode != 0:
        sys.exit(f"ERROR: usage generate markdown failed on {kdl_rel}")
    return PAGE_BANNER.format(kdl=kdl_rel) + "\n" + proc.stdout


def page_rel(bin_name: str) -> Path:
    return Path(CLI_PAGE_DIR) / f"{bin_name}.md"


def render_pages(root: Path) -> tuple[dict[str, str], list[str]]:
    """bin -> rendered page text, and the bins whose lint failed.
    Exits (actionable) when `usage` is unavailable but contracts exist."""
    kdls = contract_kdls(root)
    if not kdls:
        return {}, []
    usage = usage_binary()
    pages: dict[str, str] = {}
    failed: list[str] = []
    for bin_name, kdl_rel in kdls.items():
        text = render_page(usage, root, kdl_rel)
        if text is None:
            failed.append(bin_name)
        else:
            pages[bin_name] = text
    return pages, failed


def cmd_render(root: Path) -> int:
    """docs-kit render: write the pages (render-cli-docs' task-layer job)."""
    pages, failed = render_pages(root)
    for bin_name, text in pages.items():
        out = root / page_rel(bin_name)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(text, encoding="utf-8", newline="\n")
        print(f"  rendered {out.relative_to(root)}")
    return 1 if failed else 0


def check_rendered(root: Path) -> list[str]:
    """Lint + render to a string, compare with the committed pages. Returns
    stale descriptions (same shape as cmd_check's); never writes."""
    pages, failed = render_pages(root)
    stale = [f"lint:    {CLI_DIR}/{b}{KDL_SUFFIX}" for b in failed]
    for bin_name, text in pages.items():
        path = root / page_rel(bin_name)
        rel = str(path.relative_to(root))
        if not path.exists():
            stale.append(f"missing: {rel}")
        elif path.read_text(encoding="utf-8") != text:
            stale.append(f"stale:   {rel}")
    return stale
