"""usage-spec - build a committed Usage KDL contract from a generated core.

`docs-kit spec` drives it: the core comes from a Typer app imported in THIS
venv (dependency mode installs docs-kit in the consumer's venv, so
`<pkg>.cli:app` imports straight from here) or from stdin for Go CLIs
(`go run . --usage-spec | docs-kit spec --bin mycli`).

Generated core + curated extra. The extra's root-level nodes (`config`,
top-level `exit_code`, `example`, ...) are appended after the core; its
`cmd <path>` wrappers are spliced INSIDE the generated blocks of the matching
command path (recursively - `cmd` blocks nest, and only the nodes the extra
declares are moved), so per-command exit codes, outputs and long help ride to
their command in the generated contract.

Guards (a silent mis-merge would make the docs lie):

- core and extra must not both declare a root `config` block
- every `cmd` path the extra declares must exist in the generated core, so a
  renamed or removed command fails the merge instead of vanishing from docs
- output is byte-stable across runs, making `docs:check`'s `git diff` gate
  meaningful

Braces are counted outside strings (plain, multi-line and raw `#"..."#`) and
comments (`//`, `/* */`), so JSON in a multi-line `example` is safe. A cmd
block of the extra must put its body on its own lines (`cmd x { ... }` on one
line is refused).
"""

from __future__ import annotations

import importlib
import re
import sys

BANNER = "// @generated by usage-spec-typer from Typer metadata"

_NAME_OF_HEADER = re.compile(r"^cmd\s+(?:\"([^\"]+)\"|([A-Za-z0-9][\w-]*))")
_STRING_OPEN = re.compile(r'(#*)("""|")')
_ROOT_NODE_OF = re.compile(
    r"^(name|bin|about|long_about|version|flag|arg|cmd|include|config|output|"
    r"exit_code|example|complete|min_usage_version|alias|source|file)\b"
)
_EXPECTED_EXTRA_ROOTS = {
    "config",
    "exit_code",
    "example",
    "output",
    "complete",
    "version",
}


# ---------------------------------------------------------------------------
# tiny line-based KDL block scanner (absolute line numbering)


def _indent_of(line: str) -> int:
    return len(line) - len(line.lstrip(" "))


def _cmd_header_name(line: str) -> str | None:
    head = _NAME_OF_HEADER.match(line.lstrip())
    return (head.group(1) or head.group(2)) if head else None


def _scan(lines: list[str]) -> tuple[list[int], list[int], list[bool]]:
    """Per line: net brace count and `{` count outside strings/comments, and
    whether the line starts inside a multi-line string or block comment."""
    deltas: list[int] = []
    opens: list[int] = []
    in_string: list[bool] = []
    closer: str | None = None  # terminator of the open string/comment
    escapes = False
    for line in lines:
        in_string.append(closer is not None)
        delta = opened = 0
        i, n = 0, len(line)
        while i < n:
            if closer is not None:
                if escapes and line[i] == "\\":
                    i += 2
                elif line.startswith(closer, i):
                    i += len(closer)
                    closer = None
                else:
                    i += 1
                continue
            if line.startswith("//", i):
                break
            if line.startswith("/*", i):
                closer, escapes = "*/", False
                i += 2
                continue
            if line[i] in '#"' and (m := _STRING_OPEN.match(line, i)):
                hashes, quote = m.groups()
                closer, escapes = quote + hashes, not hashes
                i = m.end()
                continue
            if line[i] == "{":
                delta += 1
                opened += 1
            elif line[i] == "}":
                delta -= 1
            i += 1
        deltas.append(delta)
        opens.append(opened)
    return deltas, opens, in_string


def _find_cmd_blocks(
    lines: list[str], lo: int, hi: int, indent: int
) -> list[tuple[str, int, int]]:
    """cmd blocks starting at column `indent` inside lines[lo:hi] ->
    [(name, block_start, closing_brace_line)]; raises on unbalanced braces.
    Brace-less `cmd foo help="..."` (no children, as generated for empty
    commands) is its own end - it carries no body to splice into."""
    deltas, opens, in_string = _scan(lines)
    blocks: list[tuple[str, int, int]] = []
    i = lo
    while i < hi:
        if (
            not in_string[i]
            and _indent_of(lines[i]) == indent
            and (name := _cmd_header_name(lines[i])) is not None
        ):
            start = i
            if not opens[i]:
                blocks.append((name, start, start))
                i += 1
                continue
            if deltas[i] == 0:
                raise SystemExit(
                    f"ERROR: `cmd {name} {{ ... }}` on one line (line {i + 1}) - "
                    "put the block body on its own lines"
                )
            depth = 0
            while i < hi:
                depth += deltas[i]
                if depth == 0 and i > start:
                    break
                i += 1
            else:
                raise SystemExit(f"ERROR: unterminated `cmd {name}` block")
            closing = i
            blocks.append((name, start, closing))
        i += 1
    return blocks


def _cmd_paths(lines: list[str]) -> set[str]:
    """Set of space-joined command paths in a KDL document."""
    paths: set[str] = set()

    def walk(lo: int, hi: int, indent: int, prefix: tuple[str, ...]) -> None:
        for name, start, closing in _find_cmd_blocks(lines, lo, hi, indent):
            path = prefix + (name,)
            paths.add(" ".join(path))
            walk(start + 1, closing, indent + 4, path)

    walk(0, len(lines), 0, ())
    return paths


def _root_config_present(lines: list[str]) -> bool:
    in_string = _scan(lines)[2]
    return any(
        not in_string[i] and re.match(r"^config(\s|\{|$)", line)
        for i, line in enumerate(lines)
    )


def _body_indent(lines: list[str], open_line: int, closing: int, fallback: int) -> int:
    for i in range(open_line + 1, closing):
        if lines[i].strip() and not lines[i].strip().startswith("//"):
            return _indent_of(lines[i])
    return fallback


# ---------------------------------------------------------------------------
# extra parsing


def _parse_extra(text: str) -> tuple[list[str], dict[tuple[str, ...], list[str]]]:
    """Split the extra into (root-level lines with cmd blocks removed,
    body lines of every cmd block keyed by its nested path). Root cmd blocks
    must be single-statement `cmd <name> { ... }` openers at column 0."""
    lines = text.split("\n")
    bodies: dict[tuple[str, ...], list[str]] = {}

    def walk(lo: int, hi: int, indent: int, prefix: tuple[str, ...]) -> None:
        for name, start, closing in _find_cmd_blocks(lines, lo, hi, indent):
            path = prefix + (name,)
            own: list[str] = []
            i = start + 1
            nested_lo = start + 1
            nested_hi = closing
            nested_starts = [
                b[1] for b in _find_cmd_blocks(lines, nested_lo, nested_hi, indent + 4)
            ]
            idx = 0
            while i < closing:
                if idx < len(nested_starts) and i >= nested_starts[idx]:
                    # inside a nested cmd block: jump past it, collect nothing
                    blocks = _find_cmd_blocks(
                        lines, nested_starts[idx], closing, indent + 4
                    )
                    i = blocks[0][2] + 1
                    idx += 1
                    continue
                own.append(lines[i])
                i += 1
            bodies[path] = own
            walk(start + 1, closing, indent + 4, path)

    walk(0, len(lines), 0, ())

    # root lines: everything outside root-level cmd blocks (comments kept)
    root_cmd_spans = [
        (start, closing)
        for _n, start, closing in _find_cmd_blocks(lines, 0, len(lines), 0)
    ]
    root_lines: list[str] = []
    skip_until = -1
    for i, line in enumerate(lines):
        for start, closing in root_cmd_spans:
            if start <= i <= closing:
                skip_until = closing
                break
        if i <= skip_until:
            continue
        root_lines.append(line)
    return root_lines, bodies


# ---------------------------------------------------------------------------
# merge


def _reindent(body_lines: list[str], target_indent: int) -> list[str]:
    widths = [_indent_of(l) for l in body_lines if l.strip()]
    base = min(widths) if widths else 0
    out = []
    for line in body_lines:
        if line.strip():
            out.append(" " * target_indent + line[base:])
        else:
            out.append("")
    return out


def merge(core_text: str, extra_text: str | None) -> str:
    core = core_text.split("\n")
    core = _strip_leading_banner(core)
    # exporter quirk: a repeatable option with no values declares default="[]"
    # (python list repr), which renders as a literal `[]` default for users
    core = [ln.replace(' default="[]"', "").replace(" default=[]", "") for ln in core]
    if not any(l.strip() for l in core):
        raise SystemExit("ERROR: generated spec is empty")
    if not extra_text or not extra_text.strip():
        return "\n".join(core).strip("\n") + "\n"

    extra = _strip_leading_banner(extra_text.split("\n"))
    extra_text_joined = "\n".join(extra)

    if _root_config_present(extra) and _root_config_present(core):
        raise SystemExit(
            "ERROR: the generated core and the extra both declare a root `config` "
            "block - environment settings must be documented in exactly one place"
        )

    core_paths = _cmd_paths(core)
    root_lines, bodies = _parse_extra(extra_text_joined)
    for path in bodies:
        if " ".join(path) not in core_paths:
            raise SystemExit(
                f"ERROR: extra declares `cmd {' '.join(path)}` but the generated "
                "core has no such command (command or flag renamed? fix the "
                "extra; `usage lint` shows the exact path)"
            )

    merged = core
    for path in sorted(bodies, key=lambda p: -len(p)):
        merged = _splice_body(merged, list(path), bodies[path])

    root_lines = [ln for ln in root_lines if ln.strip()]
    deltas, _opens, in_string = _scan(root_lines)
    depth = 0
    for ln, delta, inside in zip(root_lines, deltas, in_string):
        statement = ln.strip()
        if inside or statement.startswith(("//", "/*")):
            depth += delta
            continue
        if depth == 0:
            m = _ROOT_NODE_OF.match(statement)
            if m is None:
                raise SystemExit(
                    f"ERROR: extra root line is not a known usage node: {statement!r}"
                )
            if m.group(1) not in _EXPECTED_EXTRA_ROOTS | {"cmd"}:
                print(
                    f"note: extra declares unexpected root node `{m.group(1)}`",
                    file=sys.stderr,
                )
        depth += delta

    out = "\n".join(merged).strip("\n")
    if root_lines:
        out += "\n\n" + "\n".join(root_lines).strip("\n") + "\n"
    else:
        out += "\n"
    return out


def _splice_body(core: list[str], path: list[str], body_lines: list[str]) -> list[str]:
    """Insert re-indented extra body lines before the closing brace of the last
    core block whose path matches (re-scans every call - cheap, and spans stay
    valid as the document grows)."""
    target = " ".join(path)
    found: tuple[int, int, int] | None = None  # (header_line, open_line, closing)

    def walk(lo: int, hi: int, indent: int, prefix: tuple[str, ...]) -> None:
        nonlocal found
        for name, start, closing in _find_cmd_blocks(core, lo, hi, indent):
            p = prefix + (name,)
            if " ".join(p) == target:
                open_line = (
                    start if closing == start else _open_line_of(core, start, closing)
                )
                found = (
                    start,
                    open_line,
                    closing,
                )  # last match wins (paths unique in practice)
            walk(start + 1, closing, indent + 4, p)

    walk(0, len(core), 0, ())
    if found is None:
        raise SystemExit(f"ERROR: cmd path {target!r} vanished while merging")
    start, _open_line, closing = found
    if closing == start:
        # a generated child-less node (`cmd x help="..."`): brace it, then fill
        header = core[start].rstrip()
        indent = " " * _indent_of(core[start])
        wrapped = [
            header + " {",
            *_reindent(body_lines, _indent_of(core[start]) + 4),
            indent + "}",
        ]
        return [ln for ln in core[:start]] + wrapped + [ln for ln in core[start + 1 :]]
    target_indent = _body_indent(core, _open_line, closing, _indent_of(core[start]) + 4)
    insert = _reindent(body_lines, target_indent)
    if any(
        core[i].strip()
        for i in range(_open_line + 1, closing)
        if not core[i].strip().startswith("//")
    ):
        insert = [""] + insert
    return core[:closing] + insert + core[closing:]


def _open_line_of(lines: list[str], start: int, closing: int) -> int:
    """Line (relative to `start`) where the block's first `{` sits."""
    for i in range(start, closing + 1):
        if "{" in lines[i]:
            return i
    raise SystemExit(f"ERROR: block starting at line {start + 1} has no {{")


def _strip_leading_banner(lines: list[str]) -> list[str]:
    i = 0
    while i < len(lines) and (
        not lines[i].strip() or lines[i].strip().startswith("//")
    ):
        i += 1
    return lines[i:]


def load_app(spec: str):
    """Import `module:attr` (dotted attributes allowed)."""
    module_name, _, attr = spec.partition(":")
    if not module_name or not attr:
        raise SystemExit(f"ERROR: expected a Typer app as 'module:app', got {spec!r}")
    obj = importlib.import_module(module_name)
    for part in attr.split("."):
        obj = getattr(obj, part)
    return obj


def typer_export(typer_app, bin_name: str) -> str:
    """Generated core for a Typer app (needs usage-spec-typer in THIS venv)."""
    try:
        from typer_usage import generate
    except ModuleNotFoundError:
        raise SystemExit(
            "ERROR: usage-spec-typer is not importable in this environment.\n"
            "Run the task through the repo's venv (uv run); it needs "
            "usage-spec-typer in [dependency-groups] dev - see "
            "docs/references/cli-standard.md."
        ) from None
    return generate(typer_app, bin_name)


def render_text(core: str, extra_text: str | None) -> str:
    """The committed file bytes for a core + optional extra (banner included)."""
    return f"{BANNER}\n" + merge(core, extra_text)
