#!/usr/bin/env python3
"""usage-spec.py - regenerate a committed Usage KDL spec from a Typer app.

Part of the docs-kit task layer: the consumer repo's `cli:spec` mise task runs
it through its own venv (which carries `usage-spec-typer`), so this file needs
nothing beyond the stdlib:

    uv run python "$DOCS_KIT/shared/mise/usage-spec.py" \
        --typer stash_watcher.cli:app --bin stash-watcher \
        --extra cli/stash-watcher.usage.extra.kdl \
        --out cli/stash-watcher.usage.kdl

The Go path reads the generated core from stdin instead of importing anything:

    go run . --usage-spec | python usage-spec.py --kdl-stdin --bin mycli

Generated core + curated extra. The extra's root-level nodes (`config`,
top-level `exit_code`, `example`, ...) are appended after the core; its
`cmd <path>` wrappers are spliced INSIDE the generated blocks of the matching
command path (recursively - `cmd` blocks nest, and only the nodes the extra
declares are moved), so per-command exit codes, outputs and long help ride to
their command in the generated contract.

Guards (a silent mis-merge would make the docs lie):

- core and extra must not both declare a root `config` block
- every `cmd` path the extra declares must exist in the generated core, so a
  renamed or removed command fails the merge instead of vanishing from docs
- output is byte-stable across runs, making `docs:check`'s `git diff` gate
  meaningful

Known KDL corner not supported: a `{` or `}` inside a single-line string in
the extra file (brace counting treats it as a block border).
"""

from __future__ import annotations

import argparse
import importlib
import re
import sys
from pathlib import Path

BANNER = "// @generated by usage-spec-typer from Typer metadata"

_CMD_HEADER = re.compile(
    r"^\s*(?:#[^\n]*\n)*\s*cmd\s+(?:\"([^\"]+)\"|([A-Za-z0-9][\w-]*))"
)
_NAME_OF_HEADER = re.compile(r"^cmd\s+(?:\"([^\"]+)\"|([A-Za-z0-9][\w-]*))")
_ROOT_NODE_OF = re.compile(
    r"^(name|bin|about|long_about|version|flag|arg|cmd|include|config|output|"
    r"exit_code|example|complete|min_usage_version|alias|source|file)\b"
)
_EXPECTED_EXTRA_ROOTS = {
    "config",
    "exit_code",
    "example",
    "output",
    "complete",
    "version",
}


# ---------------------------------------------------------------------------
# tiny line-based KDL block scanner (absolute line numbering)


def _indent_of(line: str) -> int:
    return len(line) - len(line.lstrip(" "))


def _cmd_header_name(line: str) -> str | None:
    full = _CMD_HEADER.match(line)
    if not full:
        return None
    head = _NAME_OF_HEADER.match(line.lstrip())
    if not head:
        # line was consumed as a command-word comment (// ...) -> not a cmd
        return None
    return head.group(1) or head.group(2)


def _find_cmd_blocks(
    lines: list[str], lo: int, hi: int, indent: int
) -> list[tuple[str, int, int]]:
    """cmd blocks starting at column `indent` inside lines[lo:hi] ->
    [(name, block_start, closing_brace_line)]; raises on unbalanced braces.
    Brace-less `cmd foo help="..."` (no children, as generated for empty
    commands) is its own end - it carries no body to splice into."""
    blocks: list[tuple[str, int, int]] = []
    i = lo
    while i < hi:
        if (
            _indent_of(lines[i]) == indent
            and (name := _cmd_header_name(lines[i])) is not None
        ):
            start = i
            if lines[i].count("{") - lines[i].count("}") <= 0 and "{" not in lines[i]:
                blocks.append((name, start, start))
                i += 1
                continue
            depth = 0
            while i < hi:
                depth += lines[i].count("{") - lines[i].count("}")
                if depth == 0 and i > start:
                    break
                i += 1
            else:
                raise SystemExit(f"ERROR: unterminated `cmd {name}` block")
            closing = i
            blocks.append((name, start, closing))
        i += 1
    return blocks


def _cmd_paths(lines: list[str]) -> set[str]:
    """Set of space-joined command paths in a KDL document."""
    paths: set[str] = set()

    def walk(lo: int, hi: int, indent: int, prefix: tuple[str, ...]) -> None:
        for name, start, closing in _find_cmd_blocks(lines, lo, hi, indent):
            path = prefix + (name,)
            paths.add(" ".join(path))
            walk(start + 1, closing, indent + 4, path)

    walk(0, len(lines), 0, ())
    return paths


def _root_config_present(lines: list[str]) -> bool:
    for i, line in enumerate(lines):
        if _indent_of(line) == 0 and re.match(r"^config(\s|\{|$)", line):
            return True
    return False


def _body_indent(lines: list[str], open_line: int, closing: int, fallback: int) -> int:
    for i in range(open_line + 1, closing):
        if lines[i].strip() and not lines[i].strip().startswith("#"):
            return _indent_of(lines[i])
    return fallback


# ---------------------------------------------------------------------------
# extra parsing


def _parse_extra(text: str) -> tuple[list[str], dict[tuple[str, ...], list[str]]]:
    """Split the extra into (root-level lines with cmd blocks removed,
    body lines of every cmd block keyed by its nested path). Root cmd blocks
    must be single-statement `cmd <name> { ... }` openers at column 0."""
    lines = text.split("\n")
    bodies: dict[tuple[str, ...], list[str]] = {}

    def walk(lo: int, hi: int, indent: int, prefix: tuple[str, ...]) -> None:
        for name, start, closing in _find_cmd_blocks(lines, lo, hi, indent):
            path = prefix + (name,)
            own: list[str] = []
            i = start + 1
            nested_lo = start + 1
            nested_hi = closing
            nested_starts = [
                b[1] for b in _find_cmd_blocks(lines, nested_lo, nested_hi, indent + 4)
            ]
            idx = 0
            while i < closing:
                if idx < len(nested_starts) and i > nested_starts[idx]:
                    # i already passed the block start? nested_starts holds starts
                    pass
                if idx < len(nested_starts) and i >= nested_starts[idx]:
                    # inside a nested cmd block: jump past it, collect nothing
                    blocks = _find_cmd_blocks(
                        lines, nested_starts[idx], closing, indent + 4
                    )
                    i = blocks[0][2] + 1
                    idx += 1
                    continue
                own.append(lines[i])
                i += 1
            bodies[path] = own
            walk(start + 1, closing, indent + 4, path)

    walk(0, len(lines), 0, ())

    # root lines: everything outside root-level cmd blocks (comments kept)
    root_cmd_spans = [
        (start, closing)
        for _n, start, closing in _find_cmd_blocks(lines, 0, len(lines), 0)
    ]
    root_lines: list[str] = []
    skip_until = -1
    for i, line in enumerate(lines):
        for start, closing in root_cmd_spans:
            if start <= i <= closing:
                skip_until = closing
                break
        if i <= skip_until:
            continue
        root_lines.append(line)
    return root_lines, bodies


# ---------------------------------------------------------------------------
# merge


def _reindent(body_lines: list[str], target_indent: int) -> list[str]:
    widths = [_indent_of(l) for l in body_lines if l.strip()]
    base = min(widths) if widths else 0
    out = []
    for line in body_lines:
        if line.strip():
            out.append(" " * target_indent + line[base:])
        else:
            out.append("")
    return out


def merge(core_text: str, extra_text: str | None) -> str:
    core = core_text.split("\n")
    core = _strip_leading_banner(core)
    # exporter quirk: a repeatable option with no values declares default="[]"
    # (python list repr), which renders as a literal `[]` default for users
    core = [ln.replace(' default="[]"', "").replace(" default=[]", "") for ln in core]
    if not any(l.strip() for l in core):
        raise SystemExit("ERROR: generated spec is empty")
    if not extra_text or not extra_text.strip():
        return "\n".join(core).strip("\n") + "\n"

    extra = _strip_leading_banner(extra_text.split("\n"))
    extra_text_joined = "\n".join(extra)

    if _root_config_present(extra) and _root_config_present(core):
        raise SystemExit(
            "ERROR: the generated core and the extra both declare a root `config` "
            "block - environment settings must be documented in exactly one place"
        )

    core_paths = _cmd_paths(core)
    root_lines, bodies = _parse_extra(extra_text_joined)
    for path in bodies:
        if " ".join(path) not in core_paths:
            raise SystemExit(
                f"ERROR: extra declares `cmd {' '.join(path)}` but the generated "
                "core has no such command (command or flag renamed? fix the "
                "extra; `usage lint` shows the exact path)"
            )

    merged = core
    for path in sorted(bodies, key=lambda p: -len(p)):
        merged = _splice_body(merged, list(path), bodies[path])

    root_lines = [ln for ln in root_lines if ln.strip()]
    depth = 0
    in_triple = False
    for ln in root_lines:
        statement = ln.strip()
        if statement.startswith(("//", "#")):
            continue
        if in_triple:
            # inside a multi-line KDL string: no statements, no braces to track
            if statement.count('"""') % 2 == 1:
                in_triple = False
            continue
        if depth == 0:
            m = _ROOT_NODE_OF.match(statement)
            if m is None:
                raise SystemExit(
                    f"ERROR: extra root line is not a known usage node: {statement!r}"
                )
            if m.group(1) not in _EXPECTED_EXTRA_ROOTS | {"cmd"}:
                print(
                    f"note: extra declares unexpected root node `{m.group(1)}`",
                    file=sys.stderr,
                )
        depth += ln.count("{") - ln.count("}")
        if statement.count('"""') % 2 == 1:
            in_triple = True

    out = "\n".join(merged).strip("\n")
    if root_lines:
        out += "\n\n" + "\n".join(root_lines).strip("\n") + "\n"
    else:
        out += "\n"
    return out


def _splice_body(core: list[str], path: list[str], body_lines: list[str]) -> list[str]:
    """Insert re-indented extra body lines before the closing brace of the last
    core block whose path matches (re-scans every call - cheap, and spans stay
    valid as the document grows)."""
    target = " ".join(path)
    found: tuple[int, int, int] | None = None  # (header_line, open_line, closing)

    def walk(lo: int, hi: int, indent: int, prefix: tuple[str, ...]) -> None:
        nonlocal found
        for name, start, closing in _find_cmd_blocks(core, lo, hi, indent):
            p = prefix + (name,)
            if " ".join(p) == target:
                open_line = (
                    start if closing == start else _open_line_of(core, start, closing)
                )
                found = (
                    start,
                    open_line,
                    closing,
                )  # last match wins (paths unique in practice)
            walk(start + 1, closing, indent + 4, p)

    walk(0, len(core), 0, ())
    if found is None:
        raise SystemExit(f"ERROR: cmd path {target!r} vanished while merging")
    start, _open_line, closing = found
    if closing == start:
        # a generated child-less node (`cmd x help="..."`): brace it, then fill
        header = core[start].rstrip()
        indent = " " * _indent_of(core[start])
        wrapped = [
            header + " {",
            *_reindent(body_lines, _indent_of(core[start]) + 4),
            indent + "}",
        ]
        return [ln for ln in core[:start]] + wrapped + [ln for ln in core[start + 1 :]]
    target_indent = _body_indent(core, _open_line, closing, _indent_of(core[start]) + 4)
    insert = _reindent(body_lines, target_indent)
    if any(
        core[i].strip()
        for i in range(_open_line + 1, closing)
        if not core[i].strip().startswith("//")
    ):
        insert = [""] + insert
    return core[:closing] + insert + core[closing:]


def _open_line_of(lines: list[str], start: int, closing: int) -> int:
    """Line (relative to `start`) where the block's first `{` sits."""
    for i in range(start, closing + 1):
        if "{" in lines[i]:
            return i
    raise SystemExit(f"ERROR: block starting at line {start + 1} has no {{")


def _strip_leading_banner(lines: list[str]) -> list[str]:
    i = 0
    while i < len(lines) and (
        not lines[i].strip() or lines[i].strip().startswith("//")
    ):
        i += 1
    return lines[i:]


def load_app(spec: str):
    """Import `module:attr` (dotted attributes allowed)."""
    module_name, _, attr = spec.partition(":")
    if not module_name or not attr:
        raise SystemExit(f"ERROR: --typer expects 'module:app', got {spec!r}")
    obj = importlib.import_module(module_name)
    for part in attr.split("."):
        obj = getattr(obj, part)
    return obj


# ---------------------------------------------------------------------------
# task entry


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        prog="usage-spec.py", description=__doc__.split("\n")[0]
    )
    p.add_argument(
        "--typer", metavar="MODULE:APP", help="Typer app to introspect (python path)"
    )
    p.add_argument(
        "--bin", required=True, metavar="NAME", help="CLI binary name for the spec"
    )
    p.add_argument(
        "--kdl-stdin",
        action="store_true",
        help="read the generated core from stdin (go path)",
    )
    p.add_argument("--extra", metavar="FILE", help="curated extra .kdl file")
    p.add_argument("--out", metavar="FILE", help="write here instead of stdout")
    args = p.parse_args(argv)

    if args.typer:
        try:
            from typer_usage import generate
        except ModuleNotFoundError:
            raise SystemExit(
                "ERROR: usage-spec-typer is not importable in this environment.\n"
                "Run the task through the repo's venv (uv run); it needs "
                "usage-spec-typer in [dependency-groups] dev - see "
                "docs/references/cli-standard.md."
            ) from None
        core = generate(load_app(args.typer), args.bin)
    elif args.kdl_stdin:
        core = sys.stdin.read()
    else:
        p.error("either --typer or --kdl-stdin is required")

    extra_text = None
    if args.extra:
        extra_path = Path(args.extra)
        if not extra_path.is_file():
            raise SystemExit(
                f"ERROR: extra spec {args.extra} not found; create it or drop --extra"
            )
        extra_text = extra_path.read_text(encoding="utf-8")

    text = f"{BANNER}\n" + merge(core, extra_text)
    if args.out:
        out_path = Path(args.out)
        current = out_path.read_text(encoding="utf-8") if out_path.is_file() else None
        if current == text:
            print(f"unchanged {args.out}")
            return 0
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {args.out}")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
